### PR TITLE
fix(payments): update preprocessing steps and handle session token in payment flow

### LINKED ISSUE #9946: [BUG] fix(payments): Missing reference_id error for Airwallex payments in v2 API
### Bug Description

Airwallex payments are failing in the v2 API with a "Missing connector transaction ID" error. The preprocessing step that creates the payment intent and returns the `reference_id` is not being executed in v2's payment flow.

### Expected Behavior

  When making an Airwallex payment via v2 API:

  1. **Preprocessing step executes:**
     - Request sent to: `POST {base_url}/api/v1/pa/payment_intents/create`
     - Request body includes: amount, currency, merchant_order_id
     - Response contains: `{ "id": "int_abc123...", ... }`

  2. **Reference ID is stored:**
     - The payment intent ID from preprocessing response is stored in `router_data.reference_id`

  3. **Authorize step succeeds:**
     - Request sent to: `POST {base_url}/api/v1/pa/payment_intents/int_abc123.../confirm`
     - Uses the `reference_id` from preprocessing
     - Payment processes successfully

  4. **Payment completes:**
     - Returns appropriate status (Charged, Authorized, etc.)
     - No errors related to missing transaction ID

### Actual Behavior

The preprocessing steps are not callled that's why id is not being generated and throw error `Missing connector transaction ID`

### Steps To Reproduce

Provide an unambiguous set of steps to reproduce this bug. Include code or configuration to reproduce, if relevant.

### Context For The Bug

_No response_

### Environment

Are you using hyperswitch hosted version? Yes/No
If yes, please provide the value of the `x-request-id` response header to help us debug your issue.

If not (or if building/running locally), please provide the following details:
1. Operating System or Linux distribution:
2. Rust version (output of `rustc --version`): ``
3. App version (output of `cargo r --features vergen -- --version`): ``

### Have you spent some time checking if this bug has been raised before?

- [x] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [x] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

Yes, I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by ayush22667**
## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
In Airwallex v2 payments, the create API generates a payment intent ID stored as order_id, which is then used in the confirm API to authorize the payment — if not sent, the payment fails due to an invalid or missing intent reference.Fixes Airwallex payments in v2 API by adding the missing preprocessing step call to `call_connector_service`.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

 

## Motivation and Context

closes #9946 

## How did you test it?

Payment Create:
```
curl --location 'http://localhost:8080/v2/payments' \
--header 'api-key: dev_bc4z4gWGbDMxxBnzhh3vULTEUrHAB0mm0gIjwCPoEbOcbjMKYMLO3BqHxVZ2CeyQ' \
--header 'Content-Type: application/json' \
--header 'x-profile-id: pro_lOZroioajdcVcBs6Uh0I' \
--header 'Authorization: api-key=dev_bc4z4gWGbDMxxBnzhh3vULTEUrHAB0mm0gIjwCPoEbOcbjMKYMLO3BqHxVZ2CeyQ' \
--data-raw '{
    "amount_details": {
        "order_amount": 10000,
        "currency": "USD"
    },
    "capture_method":"automatic",
    "authentication_type": "three_ds",
    "billing": {
        "address": {
            "line1": "1467",
            "line2": "Harrison Street",
            "line3": "Harrison Street",
            "city": "San Fransico",
            "state": "California",
            "zip": "94122",
            "country": "US",
            "first_name": "joseph",
            "last_name": "Doe"
        },
        "email": "example@example.com"
    },
    "shipping": {
        "address": {
            "line1": "1467",
            "line2": "Harrison Street",
            "line3": "Harrison Street",
            "city": "San Fransico",
            "state": "California",
            "zip": "94122",
            "country": "US",
            "first_name": "joseph",
            "last_name": "Doe"
        },
        "email": "example@example.com"
    },
     "payment_method_data": {
      "card": {
        "card_number": "4111111111111111",
        "card_exp_month": "10",
        "card_exp_year": "2030",
        "card_holder_name": "John Doe",
        "card_cvc": "257"
      }
    },
    "payment_method_type": "card",
    "payment_method_subtype": "credit",
     "browser_info": {
        "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
        "accept_header": "text\\/html,application\\/xhtml+xml,application\\/xml;q=0.9,image\\/webp,image\\/apng,*\\/*;q=0.8",
        "language": "en-GB",
        "color_depth": 24,
        "screen_height": 1440,
        "screen_width": 2560,
        "time_zone": -330,
        "java_enabled": true,
        "java_script_enabled": true,
        "ip_address": "0.0.0.0"
    }

}'
```
Response:
```
{
    "id": "12345_pay_019a0ad88a0c7750bd1eba5ba7aa7088",
    "status": "succeeded",
    "amount": {
        "order_amount": 10000,
        "currency": "USD",
        "shipping_cost": null,
        "order_tax_amount": null,
        "external_tax_calculation": "skip",
        "surcharge_calculation": "skip",
        "surcharge_amount": null,
        "tax_on_surcharge": null,
        "net_amount": 10000,
        "amount_to_capture": null,
        "amount_capturable": 0,
        "amount_captured": 10000
    },
    "customer_id": null,
    "connector": "airwallex",
    "created": "2025-10-22T07:35:54.636Z",
    "modified_at": "2025-10-22T07:35:56.465Z",
    "payment_method_data": {
        "billing": null
    },
    "payment_method_type": "card",
    "payment_method_subtype": "credit",
    "connector_transaction_id": "int_hkdmcft45hc9ip0vxtc",
    "connector_reference_id": "int_hkdmcft45hc9ip0vxtc",
    "merchant_connector_id": "mca_LZvkeJMiburjwketI0ro",
    "browser_info": null,
    "error": null,
    "shipping": null,
    "billing": null,
    "attempts": null,
    "connector_token_details": null,
    "payment_method_id": null,
    "next_action": null,
    "return_url": "https://google.com/success",
    "authentication_type": "three_ds",
    "authentication_type_applied": "three_ds",
    "is_iframe_redirection_enabled": null,
    "merchant_reference_id": null,
    "raw_connector_response": null,
    "feature_metadata": null,
    "metadata": null
}
```

image

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

### CODE REVIEW

File: crates/router/src/core/payments.rs [hunk 1]
```diff
@@ -4445,12 +4444,31 @@ where
...
-        is_retry_payment,
+    let mut should_continue_further =
+        tokenization::update_router_data_with_payment_method_token_result(
+            payment_method_token_response,
+            &mut router_data,
+            is_retry_payment,
+            should_continue_further,
+        );
+
+    (router_data, should_continue_further) = complete_preprocessing_steps_if_required(
```
Comment (sai-harsha-vardhan) [inline crates/router/src/core/payments.rs]: We were not planning to have generic preprocessing steps in V2 right? We thought to have specific purpose apis like CreateOrder, Authenticate etc.

File: crates/hyperswitch_connectors/src/connectors/airwallex/transformers.rs [hunk 2]
```diff
@@ -137,6 +131,32 @@ impl TryFrom<&AirwallexRouterData<&types::PaymentsPreProcessingRouterData>>
     }
 }
 
+#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
+pub struct AirwallexOrderResponse {
+    pub status: AirwallexPaymentStatus,
+    pub id: String,
+    pub amount: Option<f32>,
```
Comment (swangi-kumari) [inline crates/hyperswitch_connectors/src/connectors/airwallex/transformers.rs]:
```suggestion
    pub amount: Option<StringMajorUnit>,
```

File: crates/router/src/types.rs [hunk 3]
```diff
@@ -715,6 +715,7 @@ pub struct PaymentMethodTokenResult {
 #[derive(Clone)]
 pub struct CreateOrderResult {
     pub create_order_result: Result<String, ErrorResponse>,
+    pub reference_id: Option<String>,
```
Comment (sai-harsha-vardhan) [inline crates/router/src/types.rs]: Why do we need the reference_id?

Comment (ayush22667) [reply crates/router/src/types.rs]: remove this field in favour of `order_id`

File: crates/router/src/core/payments.rs
Comment (sai-harsha-vardhan) [inline crates/router/src/core/payments.rs:6634]: Why did we remove preprocessing steps? It may still be needed for other connectors right?

**Review by sai-harsha-vardhan — APPROVED** [review]

File: crates/router/src/core/payments.rs
Comment (ayush22667) [reply crates/router/src/core/payments.rs:6634]: it was used only for airwallex.

**Review by swangi-kumari — APPROVED** [review]
