### PR TITLE
fix: change precedence order in address that we send to ucs

### LINKED ISSUE #9268: Fix UCS address precedence order for payment method billing addresses
## Problem

The current implementation in the UCS (Unified Connector Service) transformers has incorrect precedence order when handling addresses. The unified payment method billing address should take priority over the shipping/billing addresses from the payment request.

## Current Behavior

- Shipping address: `shipping.or(unified_payment_method_billing.clone())`
- Billing address: `billing.or(unified_payment_method_billing)`

This means the payment request addresses take precedence over the unified payment method billing address.

## Expected Behavior

The unified payment method billing address should take precedence:

- Shipping address: `unified_payment_method_billing.clone().or(shipping)`
- Billing address: `unified_payment_method_billing.or(billing)`

## Impact

This affects address data consistency in UCS transformations and could lead to incorrect address information being sent to connectors.

## Files Affected

- `crates/router/src/core/unified_connector_service/transformers.rs`

### PR DESCRIPTION
**Pull request by maverox**
## Summary

This PR fixes the billing address precedence order in the UCS (Unified Connector Service) transformers to ensure that unified payment method billing addresses take priority over billing addresses from payment requests.

## Changes

- Changed billing address precedence: `unified_payment_method_billing.or(billing)` instead of `billing.or(unified_payment_method_billing)`
- Shipping address logic remains unchanged: `shipping`

## Related Issues

- Closes #9268: Fix UCS address precedence order for payment method billing addresses

## Type of Change

- [x] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation update
- [ ] Refactoring

## Testing

- [x] Code follows project style guidelines
- [x] Self-review completed
- [ ] Tests pass locally
- [ ] Documentation updated if needed

## Impact

This change ensures that unified payment method billing addresses take priority over payment request billing addresses in UCS transformations, providing more consistent address data handling.

## Files Modified

- `crates/router/src/core/unified_connector_service/transformers.rs` (line 971)

## Technical Details

The fix changes the precedence logic for billing addresses in the `ForeignTryFrom` implementation for `payments_grpc::PaymentAddress`. Previously, billing addresses from the payment request took precedence over unified payment method billing addresses. Now, if a unified payment method billing address exists, it will be used; otherwise, it falls back to the payment request billing address.

### Testing 
```sh
curl --location 'http://localhost:8080/payments' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'x-request-id: adsfadfads' \
--header 'api-key: dev_iTbySOVTqap2S4d7lr80lizI9gP4Ud3cji91v7AV1xk1elLdWNNq6dDVnSoAbpI6' \
--data-raw '{
    "amount": 6540,
    "currency": "INR",
    "amount_to_capture": 6540,
    "confirm": true,
    "profile_id": "pro_RkdjC1k2ZDLH1wvhSc76",
    "email": "customer@gmail.com",
    "capture_method": "automatic",
    
    "authentication_type": "no_three_ds",
    
    "customer": {
        "id": "customer123",
        "name": "John Doe",
        "email": "customer@gmail.com",
        "phone": "9999999999",
        "phone_country_code": "+91"
    },
    "customer_id": "customer123",
    
    
    
    
    
    "description": "Its my first payment request",
    "return_url": "https://google.com",
    "payment_method": "upi",
    "payment_method_type": "upi_collect",
    "payment_method_data": {
        "upi": {
            "upi_collect": {
                "vpa_id": "success@razorpay"
            }
        },
        "billing": {
            "email": "pmbi@example.com",
            "phone": {
                "country_code": "+91",
                "number": "6502530000"
            }
        }
    },
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
        
    
    "shipping": {
        "address": {
            "line1": "1467",
            "line2": "Harrison Street",
            "line3": "Harrison Street",
            "city": "San Fransico",
            "state": "California",
            "zip": "94122",
            "country": "IN",
            "first_name": "joseph",
            "last_name": "Doe"
        },
        "phone": {
            "number": "8056594427",
            "country_code": "+91"
        },
        "email": "si@example.com"
    },
    "statement_descriptor_name": "joseph",
    "statement_descriptor_suffix": "JS",
    "order_details": [
        {
            "product_name": "Apple iphone 15",
            "quantity": 1,
            "amount": 6540,
            "account_name": "transaction_processing"
        }
    ],
    "metadata": {
        "udf1": "value1",
        "new_customer": "true",
        "login_date": "2019-09-10T10:11:12Z"
    },
    "browser_info": {
        "user_agent": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/70.0.3538.110 Safari\/537.36",
        "accept_header": "text\/html,application\/xhtml+xml,application\/xml;q=0.9,image\/webp,image\/apng,*\/*;q=0.8",
        "language": "nl-NL",
        "color_depth": 24,
        "screen_height": 723,
        "screen_width": 1536,
        "time_zone": 0,
        "java_enabled": true,
        "java_script_enabled": true,
        "ip_address": "128.0.0.1"
    },
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    "request_incremental_authorization": false,
    "merchant_order_reference_id": "testing_the_integ03454",
    "all_keys_required": true,
    "session_expiry": 900
}'
```

```json
{
    "payment_id": "pay_d4tMeFMxF4EmZZ4w18Ym",
    "merchant_id": "merchant_1756906013",
    "status": "requires_customer_action",
    "amount": 6540,
    "net_amount": 6540,
    "shipping_cost": null,
    "amount_capturable": 6540,
    "amount_received": null,
    "connector": "razorpay",
    "client_secret": "pay_d4tMeFMxF4EmZZ4w18Ym_secret_Bj4JWSrDkGDGK3TfKBt1",
    "created": "2025-09-03T15:36:23.275Z",
    "currency": "INR",
    "customer_id": "customer123",
    "customer": {
        "id": "customer123",
        "name": "John Doe",
        "email": "customer@gmail.com",
        "phone": "9999999999",
        "phone_country_code": "+91"
    },
    "description": "Its my first payment request",
    "refunds": null,
    "disputes": null,
    "mandate_id": null,
    "mandate_data": null,
    "setup_future_usage": null,
    "off_session": null,
    "capture_on": null,
    "capture_method": "automatic",
    "payment_method": "upi",
    "payment_method_data": {
        "upi": {
            "upi_collect": {
                "vpa_id": "su*****@razorpay"
            }
        },
        "billing": {
            "address": null,
            "phone": {
                "number": "6502530000",
                "country_code": "+91"
            },
            "email": null
        }
    },
    "payment_token": null,
    "shipping": {
        "address": {
            "city": "San Fransico",
            "country": "IN",
            "line1": "1467",
            "line2": "Harrison Street",
            "line3": "Harrison Street",
            "zip": "94122",
            "state": "California",
            "first_name": "joseph",
            "last_name": "Doe",
            "origin_zip": null
        },
        "phone": {
            "number": "8056594427",
            "country_code": "+91"
        },
        "email": "si@example.com"
    },
    "billing": {
        "address": {
            "city": "San Fransico",
            "country": "IN",
            "line1": "1467",
            "line2": "Harrison Street",
            "line3": "Harrison Street",
            "zip": "94122",
            "state": "California",
            "first_name": "joseph",
            "last_name": "Doe",
            "origin_zip": null
        },
        "phone": {
            "number": "8056594427",
            "country_code": "+91"
        },
        "email": "bi@example.com"
    },
    "order_details": [
        {
            "sku": null,
            "upc": null,
            "brand": null,
            "amount": 6540,
            "category": null,
            "quantity": 1,
            "tax_rate": null,
            "product_id": null,
            "description": null,
            "product_name": "Apple iphone 15",
            "product_type": null,
            "sub_category": null,
            "total_amount": null,
            "commodity_code": null,
            "unit_of_measure": null,
            "product_img_link": null,
            "product_tax_code": null,
            "total_tax_amount": null,
            "requires_shipping": null,
            "unit_discount_amount": null
        }
    ],
    "email": "customer@gmail.com",
    "name": "John Doe",
    "phone": "9999999999",
    "return_url": "https://google.com/",
    "authentication_type": "no_three_ds",
    "statement_descriptor_name": "joseph",
    "statement_descriptor_suffix": "JS",
    "next_action": null,
    "cancellation_reason": null,
    "error_code": null,
    "error_message": null,
    "unified_code": null,
    "unified_message": null,
    "payment_experience": null,
    "payment_method_type": "upi_collect",
    "connector_label": null,
    "business_country": null,
    "business_label": "default",
    "business_sub_label": null,
    "allowed_payment_method_types": null,
    "ephemeral_key": {
        "customer_id": "customer123",
        "created_at": 1756913783,
        "expires": 1756917383,
        "secret": "epk_53d393130e224556b2105520350533ae"
    },
    "manual_retry_allowed": null,
    "connector_transaction_id": "pay_RDBFdT6qU2bwzC",
    "frm_message": null,
    "metadata": {
        "udf1": "value1",
        "login_date": "2019-09-10T10:11:12Z",
        "new_customer": "true"
    },
    "connector_metadata": null,
    "feature_metadata": {
        "redirect_response": null,
        "search_tags": null,
        "apple_pay_recurring_details": null,
        "gateway_system": "unified_connector_service"
    },
    "reference_id": "order_RDBFcufill32B5",
    "payment_link": null,
    "profile_id": "pro_RkdjC1k2ZDLH1wvhSc76",
    "surcharge_details": null,
    "attempt_count": 1,
    "merchant_decision": null,
    "merchant_connector_id": "mca_1cYyVsBadn8UVLK5vI24",
    "incremental_authorization_allowed": false,
    "authorization_count": null,
    "incremental_authorizations": null,
    "external_authentication_details": null,
    "external_3ds_authentication_attempted": false,
    "expires_on": "2025-09-03T15:51:23.275Z",
    "fingerprint": null,
    "browser_info": {
        "language": "nl-NL",
        "time_zone": 0,
        "ip_address": "128.0.0.1",
        "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36",
        "color_depth": 24,
        "java_enabled": true,
        "screen_width": 1536,
        "accept_header": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
        "screen_height": 723,
        "java_script_enabled": true
    },
    "payment_channel": null,
    "payment_method_id": null,
    "network_transaction_id": null,
    "payment_method_status": null,
    "updated": "2025-09-03T15:36:26.339Z",
    "split_payments": null,
    "frm_metadata": null,
    "extended_authorization_applied": null,
    "capture_before": null,
    "merchant_order_reference_id": "testing_the_integ03454",
    "order_tax_amount": null,
    "connector_mandate_id": null,
    "card_discovery": null,
    "force_3ds_challenge": false,
    "force_3ds_challenge_trigger": false,
    "issuer_error_code": null,
    "issuer_error_message": null,
    "is_iframe_redirection_enabled": null,
    "whole_connector_response": "{\"razorpay_payment_id\":\"pay_RDBFdT6qU2bwzC\"}",
    "enable_partial_authorization": null
}
```
**Important Note**: before fix the status was failed as it wasn't able to consume email but now it is correct

### CODE REVIEW

File: crates/router/src/core/unified_connector_service/transformers.rs [hunk 1]
```diff
@@ -967,8 +967,8 @@ impl ForeignTryFrom<hyperswitch_domain_models::payment_address::PaymentAddress>
                 }
             });
         Ok(Self {
-            shipping_address: shipping.or(unified_payment_method_billing.clone()),
-            billing_address: billing.or(unified_payment_method_billing),
+            shipping_address: unified_payment_method_billing.clone().or(shipping),
```
Comment (sai-harsha-vardhan) [inline crates/router/src/core/unified_connector_service/transformers.rs]: Why are we sending unified_payment_method_billing in shipping_address?

Comment (maverox) [reply crates/router/src/core/unified_connector_service/transformers.rs]: should I revert this? 
billing order is correct though or not?

**Review by su-shivanshmathur — APPROVED** [review]

**Review by deepanshu-iiitu — APPROVED** [review]
