### PR TITLE
docs(openapi): Fix v2 authentication headers docs

### LINKED ISSUE #10789: [BUG] v2 create customer header conflicts
### Bug Description

 curl -X POST https://sandbox.hyperswitch.io/v2/customers \
  -H "api-key: snd_{api-key omitted}" \
  -H "Content-Type: application/json" \
  -d '{
    "email": "guest@example.com",
    "name": "John Doe"
  }'
{"error":{"type":"invalid_request","message":"Missing required param: Authorization","code":"IR_04"}}

Image

v2 should only require the api-key in the header.  It fails on the demonstration documentation as well. This is a breaking issue because you cannot utilize the Payment Method Management system without a v2 customer id. 

### Expected Behavior

v2 should only require the api-key in the header.

### Actual Behavior

It sends a missing header param 'Authorization' but should not be required. 

Image

### Steps To Reproduce

Provide an unambiguous set of steps to reproduce this bug. Include code or configuration to reproduce, if relevant.
1. Go to '(https://api-reference.hyperswitch.io/v2/customers/customers--create)'
2. Try and input your api-key and customer name/email
3. See error response

### Context For The Bug

This is a breaking issue because you cannot utilize the Payment Method Management system without a v2 customer id. The PMM process fails utilizing a v1 customer_id so I tried to change to utilize the v2 method, and ran into this issue. I cannot proceed forward to utilize the SDK.

### Environment

Are you using hyperswitch hosted version? **Yes**
If yes, please provide the value of the `x-request-id` response header to help us debug your issue.
(019b5734-9491-7c51-88ee-a3325b5c6d99, 019b5732-c932-7841-a28d-6533e8421061)

### Have you spent some time checking if this bug has been raised before?

- [x] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [x] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

No, I don't have time to work on this right now

### PR DESCRIPTION
**Pull request by AnuthaDev**
## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [x] Documentation
- [ ] CI/CD

## Description

- Removed `ephemeral_key` auth from V2 openAPI docs.
- Added `jwt_key` and `publishable_key__client_secret` auth type to V2 openAPI
- Fixed auth types for V2 `payments` and `customers` endpoints

### Additional Changes

- [x] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

Closes #10789
The API documentation is wrong, the behaviour is correct.

## How did you test it?

Locally ran `mint dev` and verified API docs:

image

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [x] I added unit tests for my changes where possible

### CODE REVIEW

File: crates/openapi/src/openapi_v2.rs [hunk 1]
```diff
@@ -881,34 +881,31 @@ impl utoipa::Modify for SecurityAddon {
                 (
                     "api_key",
                     SecurityScheme::ApiKey(ApiKey::Header(ApiKeyValue::with_description(
-                        "api-key",
-                        "Use the API key created under your merchant account from the HyperSwitch dashboard. API key is used to authenticate API requests from your merchant server only. Don't expose this key on a website or embed it in a mobile application."
+                        "Authorization",
+                        "Format: api-key=<api_key>\n\nUse the API key created under your merchant account from the HyperSwitch dashboard. API key is used to authenticate API requests from your merchant server only. Don't expose this key on a website or embed it in a mobile application."
```
Comment (SanchithHegde) [inline crates/openapi/src/openapi_v2.rs]: Nit: Can probably try enclosing the format in backticks, if it renders correctly.


```suggestion
                        "Format: `api-key=<api_key>`\n\nUse the API key created under your merchant account from the HyperSwitch dashboard. API key is used to authenticate API requests from your merchant server only. Don't expose this key on a website or embed it in a mobile application."
```

**Review by sai-harsha-vardhan — APPROVED** [review]
