### PR TITLE
fix(dashboard_metadata): mask `poc_email` and `data_value` for DashboardMetadata

### LINKED ISSUE #7128: feat(diesel_models, api_models): mask `poc_email` and `dashboard_value` for DashboardMetadata
## Current behaviour

- `poc_email` isn't masked for `DashboardMetadata` which leads to it being logged both at API and diesel query level.
Example:

Image

## Proposed Changes

- (api_models): change the `poc_email` type to `Secret<String>` 
  - Add some `pii::Email` validation to check for input validity
- (diesel_models): change `data_value` to `Secret<serde_json::Value>`

### PR DESCRIPTION
**Pull request by maverox**
## Type of Change

- [x] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

- (api_models): change the `poc_email` type to `Secret<String>` 
  - Add some `pii::Email` validation to check for input validity
- (diesel_models): change `data_value` to `Secret<serde_json::Value>`

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

`poc_email` isn't masked for `DashboardMetadata` which leads to it being logged both at API and diesel query level.

Example:
Image

## How did you test it?

Curl to set metadata:
```bash
curl --location 'http://localhost:8080/user/data' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer {{TOKEN}}' \
--data '
{
    "ProdIntent": {
        "is_completed": true,
        "legal_business_name": "test",
        "business_label": "test",
        "business_location": "US",
        "display_name": "test",
        "poc_email": "test@gmail.com",
        "business_type": "test",
        "business_identifier": "test",
        "business_website": "test",
        "poc_name": "test",
        "poc_contact": "test",
        "comments": "test"
    }
} 
'
```
Result: 

Screenshot 2025-01-28 at 3 03 49 PM

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

### CODE REVIEW

File: crates/router/src/core/user/dashboard_metadata.rs [hunk 1]
```diff
@@ -447,6 +450,11 @@ async fn insert_metadata(
             metadata
         }
         types::MetaData::ProdIntent(data) => {
+            if let Some(poc_email) = &data.poc_email {
+                let inner_poc_email = poc_email.peek().as_str();
+                common_utils::pii::Email::from_str(inner_poc_email)
```
Comment (ThisIsMani) [inline crates/router/src/core/user/dashboard_metadata.rs:455]: Import `common_utils` separately.
```suggestion
                pii::Email::from_str(inner_poc_email)
```

File: crates/router/src/core/user/dashboard_metadata.rs [hunk 2]
```diff
@@ -447,6 +451,11 @@ async fn insert_metadata(
             metadata
         }
         types::MetaData::ProdIntent(data) => {
+            if let Some(poc_email) = &data.poc_email {
+                let inner_poc_email = poc_email.peek().as_str();
+                pii::Email::from_str(inner_poc_email)
```
Comment (ThisIsMani) [inline crates/router/src/core/user/dashboard_metadata.rs:456]: Can't we use this: https://github.com/juspay/hyperswitch/blob/c02cb20b02501eb027e61e4f4a342eeda1fb9b70/crates/common_utils/src/pii.rs#L232

**Review by ThisIsMani — APPROVED** [review]

**Review by apoorvdixit88 — APPROVED** [review]
May be we can try not to mask `data_value`.

**Review by Riddhiagrawal001 — APPROVED** [review]
