### PR TITLE
fix(api): align ApiEvent status_code with HTTP response when proxy_connector_http_status_code enabled

### LINKED ISSUE #10681: [BUG] ApiEvent status_code always logs 200 when proxy_connector_http_status_code is enabled
### Bug Description

When `proxy_connector_http_status_code = true` is enabled in configuration, the `ApiEvent` logged via `server_wrap_util()` always records `status_code: 200` for `JsonWithHeaders` responses, even when the actual HTTP response returns a different status code (400, 500, etc.) from the connector.

This causes a mismatch between:
- **ApiEvent logs**: Always shows `status_code: 200`
- **Actual HTTP response**: Shows the connector's status code (e.g., 400, 500)

### Expected Behavior

When `proxy_connector_http_status_code` is enabled, the `ApiEvent` should log the same status code that is returned in the HTTP response to the client.

### Actual Behavior

The `ApiEvent` always logs `status_code: 200` for `JsonWithHeaders` responses because:

1. `server_wrap_util()` determines status code using `track_response_status_code()` at line 306
2. `track_response_status_code()` always returns `200` for `JsonWithHeaders` responses
3. The actual HTTP status from connector is only extracted LATER in `server_wrap()` (lines 522-560)
4. By that time, the `ApiEvent` has already been logged with status `200`

### Steps To Reproduce

1. Enable `proxy_connector_http_status_code = true` in config
2. Make a payment request that triggers a connector error (400, 500, etc.)
3. Check ApiEvent logs - status_code will be 200
4. Check HTTP response - status code will be the actual connector error code

### Impact

- Data pipeline inconsistencies
- Analytics showing incorrect success rates
- Monitoring/alerting based on ApiEvent status codes will miss errors

### Root Cause

**File:** `crates/router/src/services/api.rs`

The status code extraction happens in different functions:
- `server_wrap_util()` logs ApiEvent with status from `track_response_status_code()` (always 200)
- `server_wrap()` extracts actual connector status from `X_CONNECTOR_HTTP_STATUS_CODE` header later

### Proposed Solution

Extract the connector HTTP status code from headers in `server_wrap_util()` BEFORE logging the ApiEvent.

### Environment

- Hyperswitch version: main branch
- Feature flag: `proxy_connector_http_status_code = true`

### Have you spent some time checking if this bug has been raised before?

- [x] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [x] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

- [x] Yes, I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by maverox**
## Summary

Fixes #10681

Fixes inconsistency between ApiEvent logged status_code and actual HTTP response status when `proxy_connector_http_status_code` feature is enabled.

**Problem:** When `proxy_connector_http_status_code = true`, the ApiEvent was always logging `status_code: 200` for `JsonWithHeaders` responses, even when the actual HTTP response returned a different status code (400, 500, etc.) from the connector. This caused data pipeline inconsistencies where analytics showed 200 status codes but actual responses had error codes.

**Root Cause:** The status code was determined in `server_wrap_util()` using `track_response_status_code()` which always returns 200 for `JsonWithHeaders`. The actual HTTP status from the connector was only extracted later in `server_wrap()` when building the HTTP response.

**Solution:** Extract the connector HTTP status code from response headers in `server_wrap_util()` BEFORE logging the ApiEvent, ensuring the logged status code matches the actual HTTP response.

## Changes

- Added `extract_connector_http_status_code()` method to `ProxyStatusMapping` impl block in `crates/router/src/configs/settings.rs`
  - Returns `Option<http::StatusCode>` directly
  - Encapsulates the feature flag check and header parsing logic
- Modified `server_wrap_util()` in `crates/router/src/services/api.rs` to use the new method when logging ApiEvent for `JsonWithHeaders` responses
- Refactored `server_wrap()` to use the same method, removing duplicated code

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [x] Refactoring (code cleanup, no functional changes beyond the fix)

## Testing

- [x] Code compiles without errors (`cargo check -p router --lib`)
- [ ] Manual testing with `proxy_connector_http_status_code = true` enabled
- Validation steps:
  1. Enable `proxy_connector_http_status_code = true` in config
  2. Make payment request that triggers connector error (400, 500)
  3. Verify ApiEvent `status_code` matches actual HTTP response status

## Behavior After Fix

| Scenario | Before | After |
|----------|--------|-------|
| Feature disabled | ApiEvent: 200, HTTP: 200 | No change |
| Feature enabled, connector returns 200 | ApiEvent: 200, HTTP: 200 | No change |
| Feature enabled, connector returns 400 | ApiEvent: **200** ❌, HTTP: 400 | ApiEvent: **400** ✅, HTTP: 400 |
| Feature enabled, connector returns 500 | ApiEvent: **200** ❌, HTTP: 500 | ApiEvent: **500** ✅, HTTP: 500 |

## Future Work (Other Inconsistencies Identified)

During investigation, we identified additional inconsistencies that should be addressed separately:

### 1. Webhook Event Logging - Hardcoded Status 200
**Location:** `crates/router/src/core/webhooks/incoming.rs` (~lines 134, 196)

All webhook events are logged with `status_code: 200`, even when webhook processing fails or returns error responses.

### 2. X_HS_LATENCY Header Inconsistency
**Location:** `crates/router/src/services/api.rs:334-338` and `658-665`

The latency header value logged in ApiEvent differs from the transformed value sent to the client (`request_duration - external_latency`).

## Checklist

- [x] Code follows project style guidelines
- [x] Self-review completed
- [x] Code compiles and passes `cargo check`
- [ ] Tests pass locally
- [ ] Documentation updated if needed

### CODE REVIEW

**Comment by maverox** [comment]
Fixes #10681

File: crates/router/src/services/api.rs [hunk 1]
```diff
@@ -149,6 +149,44 @@ pub enum AuthFlow {
     Merchant,
 }
 
+/// Extracts the connector HTTP status code from response headers when proxy_connector_http_status_code is enabled.
+/// Returns None if the feature is disabled, the header is missing, or if parsing fails.
+fn extract_connector_http_status_code(
```
Comment (hrithikesh026) [inline crates/router/src/services/api.rs]: can be a impl on `struct ProxyStatusMapping`
