### PR TITLE
fix(cypress): fix itaubank, datatrans and facilitapay

### LINKED ISSUE #8230: [CYPRESS] Fix Cypress connector failures
Wise
Elavon
Paybox
Datatrans
Facilitapay
Itaubank

### PR DESCRIPTION
**Pull request by pixincreate**
## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [x] CI/CD

## Description

This PR fixes Cypress tests for Itaubank, Paybox and Datatrans.

Datatrans still fail. Datatrans fails because `ResponseCustom` needs a refactor while Paybox requires us to pass `FR` as country and upon fixing it, it started to say wrong creds.

Facilitapay has no issues. Wise and Elavon creds issue.

JP Morgan addressed in https://github.com/juspay/hyperswitch/pull/8282

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

Fix stuff. Closes #8230 

## How did you test it?

|command|screenshot|
|-|-|
|`CYPRESS_CONNECTOR=itaubank npm run cypress:payments`|image|
|`CYPRESS_CONNECTOR=datatrans npm run cypress:payments`|image|
|`CYPRESS_CONNECTOR=facilitapay npm run cypress:payments`|image|

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

### CODE REVIEW

**Comment by Gnanasundari24** [comment]
@pixincreate Add entire testcases screenshot for paybox and other connectors

File: cypress-tests/cypress/e2e/configs/Payment/Datatrans.js [hunk 1]
```diff
@@ -1,11 +1,103 @@
...
+    card_exp_month: "06",
+    card_exp_year: "28",
+    card_holder_name: "joseph Doe",
+    payment_checks: null,
+    authentication_data: null,
+  },
+  billing: null,
+};
+
+const billing_with_newline = {
```
Comment (likhinbopanna) [inline cypress-tests/cypress/e2e/configs/Payment/Datatrans.js]: Can you make it camelCase ?

File: cypress-tests/cypress/e2e/configs/Payment/Datatrans.js [hunk 2]
```diff
@@ -1,11 +1,103 @@
...
+    card_exp_month: "06",
+    card_exp_year: "28",
+    card_holder_name: "joseph Doe",
+    payment_checks: null,
+    authentication_data: null,
+  },
+  billing: null,
+};
+
+const payment_method_data_no3ds = {
```
Comment (likhinbopanna) [inline cypress-tests/cypress/e2e/configs/Payment/Datatrans.js]: Can you make it camelCase?

File: cypress-tests/cypress/e2e/configs/Payment/Datatrans.js [hunk 3]
```diff
@@ -122,5 +288,393 @@ export const connectorDetails = {
...
+      },
+      Response: {
+        status: 200,
+        body: {
+          status: "requires_payment_method",
+          setup_future_usage: "off_session",
+        },
+      },
+    },
+
```
Comment (likhinbopanna) [inline cypress-tests/cypress/e2e/configs/Payment/Datatrans.js]: Can you remove space line

File: cypress-tests/cypress/e2e/configs/Payment/Datatrans.js [hunk 4]
```diff
@@ -122,5 +288,393 @@ export const connectorDetails = {
...
+      Request: {
+        payment_method: "card",
+        payment_method_data: {
+          card: successfulNo3DSCardDetails,
+        },
+        currency: "USD",
+        mandate_data: singleUseMandateData,
+      },
+      Response: {
+        trigger_skip: true,
```
Comment (likhinbopanna) [inline cypress-tests/cypress/e2e/configs/Payment/Datatrans.js]: Can you remove this trigger_skip as you passed in the Configs

File: cypress-tests/cypress/e2e/configs/Payment/Datatrans.js [hunk 5]
```diff
@@ -122,5 +288,393 @@ export const connectorDetails = {
...
+        setup_future_usage: "off_session",
+        customer_acceptance: customerAcceptance,
+      },
+      Response: {
+        status: 200,
+        body: {
+          status: "requires_customer_action",
+        },
+      },
+      ResponseCustom: {
```
Comment (likhinbopanna) [inline cypress-tests/cypress/e2e/configs/Payment/Datatrans.js:563]: Why this is required ? it should go to requires_customer_action?

Comment (pixincreate) [reply cypress-tests/cypress/e2e/configs/Payment/Datatrans.js:563]: this is kept intentionally. the connector randomly sends `requires_customer_action` and `succeeded`. tried with multiple cards, none of them worked as expected.  

we would want to refactor the cypress core such that responseCustom is handled is properly. at present, it gets ignored.
