### PR TITLE
fix: Resolved issue of webhooks response from ucs

### LINKED ISSUE #9027: [BUG] There is a bug when the webhook response comes from ucs
### Bug Description

There is a bug when the webhook response comes from ucs,
the code was not able to deserialize the response

### Expected Behavior

webhook response form ucs should be handle using ucs logic

### Actual Behavior

a webhook failed

### Steps To Reproduce

Provide an unambiguous set of steps to reproduce this bug. Include code or configuration to reproduce, if relevant.

### Context For The Bug

_No response_

### Environment

Are you using hyperswitch hosted version? Yes/No
If yes, please provide the value of the `x-request-id` response header to help us debug your issue.

If not (or if building/running locally), please provide the following details:
1. Operating System or Linux distribution:
2. Rust version (output of `rustc --version`): ``
3. App version (output of `cargo r --features vergen -- --version`): ``

### Have you spent some time checking if this bug has been raised before?

- [x] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [x] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

None

### PR DESCRIPTION
**Pull request by AmitsinghTanwar007**
## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
while handling the response of UCS for webhooks Hyperswitch used to use the existing connector code (Psync's Handle Respnse) which gave error for UCS response so fixed this issue.
Closes #9027 

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## How did you test it?

testing of the webhook can be done by the step in this merged PR:https://github.com/juspay/hyperswitch/pull/8814

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

### CODE REVIEW

File: crates/router/src/core/unified_connector_service/transformers.rs [hunk 1]
```diff
@@ -1230,13 +1231,57 @@ pub fn transform_ucs_webhook_response(
     response: PaymentServiceTransformResponse,
 ) -> Result<WebhookTransformData, error_stack::Report<errors::ApiErrorResponse>> {
     let event_type = match response.event_type {
-        0 => api_models::webhooks::IncomingWebhookEvent::PaymentIntentSuccess,
+        0 => api_models::webhooks::IncomingWebhookEvent::EventNotSupported,
```
Comment (hrithikesh026) [inline crates/router/src/core/unified_connector_service/transformers.rs]: This logic can be moved into a impl function on `IncomingWebhookEvent`

File: crates/router/src/services/api.rs [hunk 2]
```diff
@@ -165,6 +165,54 @@ where
             };
             connector_integration.handle_response(req, None, response)
         }
+        payments::CallConnectorAction::UCSHandleResponse(transform_data_bytes) => {
```
Comment (hrithikesh026) [inline crates/router/src/services/api.rs:245]: lets move this logic to a separate function

**Review by hrithikesh026 — APPROVED** [review]

File: crates/router/src/services/api.rs [hunk 3]
```diff
@@ -127,6 +127,64 @@ pub type BoxedBillingConnectorPaymentsSyncIntegrationInterface<T, Req, Res> =
...
+fn handle_ucs_response<T, Req, Resp>(
+    router_data: types::RouterData<T, Req, Resp>,
+    transform_data_bytes: Vec<u8>,
+) -> CustomResult<types::RouterData<T, Req, Resp>, errors::ConnectorError>
+where
+    T: Clone + Debug + 'static,
+    Req: Debug + Clone + 'static,
+    Resp: Debug + Clone + 'static,
+{
+    let webhook_transform_data: crate::core::unified_connector_service::WebhookTransformData =
```
Comment (jarnura) [inline crates/router/src/services/api.rs]:
```suggestion
    let webhook_transform_data: unified_connector_service::WebhookTransformData =
```

File: crates/router/src/services/api.rs [hunk 4]
```diff
@@ -127,6 +127,64 @@ pub type BoxedBillingConnectorPaymentsSyncIntegrationInterface<T, Req, Res> =
...
+        .webhook_content
+        .ok_or(errors::ConnectorError::ResponseDeserializationFailed)
+        .attach_printable("UCS webhook transform data missing webhook_content")?;
+
+    let payment_get_response = match webhook_content.content {
+        Some(unified_connector_service_client::payments::webhook_response_content::Content::PaymentsResponse(payments_response)) => {
+            payments_response
+        },
+        Some(unified_connector_service_client::payments::webhook_response_content::Content::RefundsResponse(_)) => {
+            return Err(errors::ConnectorError::ProcessingStepFailed(Some("UCS webhook contains refund response but payment processing was expected".to_string().into())).into());
```
Comment (jarnura) [inline crates/router/src/services/api.rs]: Use ? to throw error, don't use return

File: crates/router/src/services/api.rs [hunk 5]
```diff
@@ -127,6 +127,64 @@ pub type BoxedBillingConnectorPaymentsSyncIntegrationInterface<T, Req, Res> =
...
+        },
+        Some(unified_connector_service_client::payments::webhook_response_content::Content::DisputesResponse(_)) => {
+            return Err(errors::ConnectorError::ProcessingStepFailed(Some("UCS webhook contains dispute response but payment processing was expected".to_string().into())).into());
```
Comment (jarnura) [inline crates/router/src/services/api.rs]: Use ? to throw error, don't use return

File: crates/router/src/services/api.rs [hunk 6]
```diff
@@ -127,6 +127,64 @@ pub type BoxedBillingConnectorPaymentsSyncIntegrationInterface<T, Req, Res> =
...
+        },
+        None => {
+            return Err(errors::ConnectorError::ResponseDeserializationFailed)
```
Comment (jarnura) [inline crates/router/src/services/api.rs]: Use ? to throw error, don't use return

File: crates/router/src/services/api.rs [hunk 7]
```diff
@@ -127,6 +127,64 @@ pub type BoxedBillingConnectorPaymentsSyncIntegrationInterface<T, Req, Res> =
...
+                .attach_printable("UCS webhook content missing payments_response");
+        }
+    };
+
+    let (status, router_data_response, status_code) =
+        crate::core::unified_connector_service::handle_unified_connector_service_response_for_payment_get(payment_get_response.clone())
```
Comment (jarnura) [inline crates/router/src/services/api.rs]:
```suggestion
        unified_connector_service::handle_unified_connector_service_response_for_payment_get(payment_get_response.clone())
```

File: crates/router/src/services/api.rs [hunk 8]
```diff
@@ -127,6 +127,64 @@ pub type BoxedBillingConnectorPaymentsSyncIntegrationInterface<T, Req, Res> =
...
+            .change_context(errors::ConnectorError::ProcessingStepFailed(None))
+            .attach_printable("Failed to process UCS webhook response using PSync handler")?;
+
+    let mut updated_router_data = router_data;
+    updated_router_data.status = status;
+
+    match router_data_response {
```
Comment (jarnura) [inline crates/router/src/services/api.rs]: use map_err, follow idiomatic ways of writing

**Review by hrithikesh026 — APPROVED** [review]

**Review by jarnura — APPROVED** [review]
