### PR TITLE
fix(core/payouts): Fix payouts void logic and response handling for wallets

### LINKED ISSUE #10623: [BUG] Payouts
### Bug Description

1. Void flow - For connectors that support instant payout only
* Create and confirm the payout 
* Make a void call
This make a void call to the connector - instead it should have been cancelled at hyperswitch end (because for the ones that support instant payouts , no call was made to the connector yet)
 
2. In case of payouts via wallets -  at the time of deserializing and constructing the response - no matter which wallet was used we always got the paypal struct in response:
```

"payout_method_data": {
        "wallet": {
            "email": null,
            "telephone_number": null,
            "paypal_id": null
        }
    }

```

This is because the struct for WalletAdditionalData was marked untagged and all the fields for PaypalAdditionalData was optional, so every struct was getting serialized to paypal's.
```

#[derive(
    Eq, PartialEq, Clone, Debug, Deserialize, Serialize, FromSqlRow, AsExpression, ToSchema,
)]
#[diesel(sql_type = Jsonb)]
#[serde(untagged)]
pub enum WalletAdditionalData {
    /// Additional data for paypal wallet payout method
    Paypal(Box<PaypalAdditionalData>),
    /// Additional data for venmo wallet payout method
    Venmo(Box<VenmoAdditionalData>),
    /// Additional data for Apple pay decrypt wallet payout method
    ApplePayDecrypt(Box<ApplePayDecryptAdditionalData>),

```

### Expected Behavior

1. In this case, we shouldn't make the call to the connector, instead cancel it at our end.
To address this, we are adding a check - we wont make a void call to the connector if the status is `RequiresFulfillment` and it supports instant payout.
2. To address this response handling, we are changing the way PaypalAdditionalData struct is parsed, For payout via paypal, only one of the field should be present - so either we will receive email or telephone or paypal_id.
We are changing the struct to enum :
```

#[serde(tag = "flow_type", rename_all = "snake_case")]
pub enum PaypalAdditionalData {
    /// Email linked with paypal account
    #[schema(example = "john.doe@example.com")]
    Email {
        /// Email linked with paypal account
        email: MaskedEmail
    },
    /// mobile number linked to paypal account
    #[schema(example = "*******3349")]
    TelephoneNumber {
        /// mobile number linked to paypal account
        telephone_number: MaskedPhoneNumber
    },
    /// id of the paypal account
    #[schema(example = "G83K*****HCQ2")]
    PaypalId {
        /// id of the paypal account
        paypal_id: MaskedBankAccount
    },
}

```

and the WalletAdditionalData would look like : 
```
pub enum WalletAdditionalData {
    ApplePayDecrypt(Box<ApplePayDecryptAdditionalData>),
    Paypal(Box<PaypalAdditionalData>),
    Venmo(Box<VenmoAdditionalData>),
}

```

### Actual Behavior

1. In this case, we shouldn't make the call to the connector, instead cancel it at our end.
To address this, we are adding a check - we wont make a void call to the connector if the status is `RequiresFulfillment` and it supports instant payout.
2. To address this response handling, we are changing the way PaypalAdditionalData struct is parsed, For payout via paypal, only one of the field should be present - so either we will receive email or telephone or paypal_id.
We are changing the struct to enum :
```

#[serde(tag = "flow_type", rename_all = "snake_case")]
pub enum PaypalAdditionalData {
    /// Email linked with paypal account
    #[schema(example = "john.doe@example.com")]
    Email {
        /// Email linked with paypal account
        email: MaskedEmail
    },
    /// mobile number linked to paypal account
    #[schema(example = "*******3349")]
    TelephoneNumber {
        /// mobile number linked to paypal account
        telephone_number: MaskedPhoneNumber
    },
    /// id of the paypal account
    #[schema(example = "G83K*****HCQ2")]
    PaypalId {
        /// id of the paypal account
        paypal_id: MaskedBankAccount
    },
}

```

and the WalletAdditionalData would look like : 
```
pub enum WalletAdditionalData {
    ApplePayDecrypt(Box<ApplePayDecryptAdditionalData>),
    Paypal(Box<PaypalAdditionalData>),
    Venmo(Box<VenmoAdditionalData>),
}

```

### Steps To Reproduce

Provide an unambiguous set of steps to reproduce this bug. Include code or configuration to reproduce, if relevant.

### Context For The Bug

_No response_

### Environment

Are you using hyperswitch hosted version? Yes/No
If yes, please provide the value of the `x-request-id` response header to help us debug your issue.

If not (or if building/running locally), please provide the following details:
1. Operating System or Linux distribution:
2. Rust version (output of `rustc --version`): ``
3. App version (output of `cargo r --features vergen -- --version`): ``

### Have you spent some time checking if this bug has been raised before?

- [x] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [x] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

Yes, I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by Vani-1107**
## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

#10623 

### Additional Changes

- [x] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

#10623 

## How did you test it?

1) Payouts - applepay decrypt flow:

Request:
```

{
    "amount": 100,
    "currency": "GBP",
    "customer_id": "payout_customer1",
    "email": "payout_customer@example.com",
    "name": "John Doe",
    "phone": "999999999",
    "phone_country_code": "+65",
    "description": "Its my first payout request",
    "payout_type": "wallet",
    "payout_method_data": {
        "wallet": {
            "apple_pay_decrypt": {
                "dpan": "4444333322221111",
                "expiry_month": "05",
                "expiry_year": "2035",
                "card_holder_name": "John Appleseed",
                "card_network": "Visa"
            }
        }
    },
    "billing": {
        "address": {
            "city": "Los Angeles",
            "country": "US",
            "line1": "123 Main St",
            "line2": "Apt 4B",
            "zip": "90001",
            "state": "CA",
            "first_name": "John",
            "last_name": "Doe"
        }
    },
    "entity_type": "Individual",
    "recurring": false,
    "auto_fulfill": true,
    "confirm": true
}

```

Response(we shouldn't we getting email, telephone_number and paypal_id when payout method is applepay):

```

{
    "payout_id": "payout_OLN3ul6QUhvKpNMH7dyH",
    "merchant_id": "merchant_1765451766",
    "merchant_order_reference_id": null,
    "amount": 100,
    "currency": "GBP",
    "connector": "worldpayxml",
    "payout_type": "wallet",
    "payout_method_data": {
        "wallet": {
            "card_exp_month": "05",
            "card_exp_year": "2035",
            "card_holder_name": "John Appleseed"
        }
    },
    "billing": {
        "address": {
            "city": "Los Angeles",
            "country": "US",
            "line1": "123 Main St",
            "line2": "Apt 4B",
            "line3": null,
            "zip": "90001",
            "state": "CA",
            "first_name": "John",
            "last_name": "Doe",
            "origin_zip": null
        },
        "phone": null,
        "email": null
    },
    "auto_fulfill": true,
    "customer_id": "payout_customer1",
    "customer": {
        "id": "payout_customer1",
        "name": "John Doe",
        "email": "payout_customer@example.com",
        "phone": "999999999",
        "phone_country_code": "+65"
    },
    "client_secret": "payout_payout_OLN3ul6QUhvKpNMH7dyH_secret_y4PR418RxR8fwNZYEsol",
    "return_url": null,
    "business_country": null,
    "business_label": null,
    "description": "Its my first payout request",
    "entity_type": "Individual",
    "recurring": false,
    "metadata": {},
    "merchant_connector_id": "mca_jX0wlGsB9NYD9FPIhagn",
    "status": "initiated",
    "error_message": null,
    "error_code": null,
    "profile_id": "pro_Js7WcBCrnlkRkNQRA4YR",
    "created": "2025-12-11T11:16:25.291Z",
    "connector_transaction_id": "payout_OLN3ul6QUhvKpNMH7dyH_1",
    "priority": null,
    "payout_link": null,
    "email": "payout_customer@example.com",
    "name": "John Doe",
    "phone": "999999999",
    "phone_country_code": "+65",
    "unified_code": null,
    "unified_message": null,
    "payout_method_id": null
}

```

Payouts: (payout method - paypal)

```

{
    "amount": 1,
    "currency": "EUR",
    "customer_id": "payout_customer",
    "email": "payout_customer@example.com",
    "name": "John Doe",
    "phone": "999999999",
    "phone_country_code": "+65",
    "description": "Its my first payout request",
    "payout_type": "wallet",
    "payout_method_data": {
        "wallet": {
            "paypal": {
                "email": "sk.sakil@juspay.in"
            }
        }
    },
    "billing": {
        "address": {
            "line1": "1467",
            "line2": "Harrison Street",
            "line3": "Harrison Street",
            "city": "San Fransico",
            "state": "NY",
            "zip": "94122",
            "country": "US",
            "first_name": "John",
            "last_name": "Doe"
        },
        "phone": {
            "number": "8056594427",
            "country_code": "+91"
        }
    },
    "entity_type": "NaturalPerson",
    "recurring": false,
    "metadata": {
        "ref": "123"
    },
    "routing": {
        "type": "single",
        "data": "paypal"
    },
    "confirm": true,
    "auto_fulfill": false
}

```

Response:

```

{
    "payout_id": "payout_8GsaJTfO7ZoPbbZ1Czmy",
    "merchant_id": "merchant_1765452119",
    "merchant_order_reference_id": null,
    "amount": 1,
    "currency": "EUR",
    "connector": "paypal",
    "payout_type": "wallet",
    "payout_method_data": {
        "wallet": {
            "field_type": "email",
            "email": "sk******@juspay.in"
        }
    },
    "billing": {
        "address": {
            "city": "San Fransico",
            "country": "US",
            "line1": "1467",
            "line2": "Harrison Street",
            "line3": "Harrison Street",
            "zip": "94122",
            "state": "NY",
            "first_name": "John",
            "last_name": "Doe",
            "origin_zip": null
        },
        "phone": {
            "number": "8056594427",
            "country_code": "+91"
        },
        "email": null
    },
    "auto_fulfill": false,
    "customer_id": "payout_customer",
    "customer": {
        "id": "payout_customer",
        "name": "John Doe",
        "email": "payout_customer@example.com",
        "phone": "999999999",
        "phone_country_code": "+65"
    },
    "client_secret": "payout_payout_8GsaJTfO7ZoPbbZ1Czmy_secret_ZWUCsmumRtlwu2Xwo0zZ",
    "return_url": null,
    "business_country": null,
    "business_label": null,
    "description": "Its my first payout request",
    "entity_type": "NaturalPerson",
    "recurring": false,
    "metadata": {
        "ref": "123"
    },
    "merchant_connector_id": "mca_dWf7cfCIz2XGsJoZnrMy",
    "status": "requires_fulfillment",
    "error_message": null,
    "error_code": null,
    "profile_id": "pro_8xzjj3yyejCtwYZQ6pH5",
    "created": "2025-12-11T11:22:33.906Z",
    "connector_transaction_id": null,
    "priority": null,
    "payout_link": null,
    "email": "payout_customer@example.com",
    "name": "John Doe",
    "phone": "999999999",
    "phone_country_code": "+65",
    "unified_code": null,
    "unified_message": null,
    "payout_method_id": null
}

```

Void: 

Create+Confirm (worldpayxml):

```

{
    "amount": 100,
    "currency": "GBP",
    "customer_id": "payout_customer11",
    "email": "payout_customer@example.com",
    "name": "John Doe",
    "phone": "999999999",
    "phone_country_code": "+65",
    "description": "Its my first payout request",
    "payout_type": "card",
    "payout_method_data": {
        "card": {
            "card_number" : "4444333322221111",
            "expiry_month": "12",
            "expiry_year": "2025",
            "card_holder_name": "CL-BRW1",
            "card_network": "Visa"
        }
    },
    "billing": {
        "address": {
            "city": "Los Angeles",
            "country": "US",
            "line1": "123 Main St",
            "line2": "Apt 4B",
            "zip": "90001",
            "state": "CA",
            "first_name": "John",
            "last_name": "Doe"
        }
    },
    "entity_type": "Individual",
    "recurring": true,
    "auto_fulfill": false,
    "confirm": true
}

```

Response of create+confirm:

```

{
    "payout_id": "payout_gIUzolKdK7WVdkS7s8LN",
    "merchant_id": "merchant_1765451766",
    "merchant_order_reference_id": null,
    "amount": 100,
    "currency": "GBP",
    "connector": "worldpayxml",
    "payout_type": "card",
    "payout_method_data": {
        "card": {
            "card_issuer": null,
            "card_network": "Visa",
            "card_type": null,
            "card_issuing_country": null,
            "bank_code": null,
            "last4": "1111",
            "card_isin": "444433",
            "card_extended_bin": null,
            "card_exp_month": "12",
            "card_exp_year": "2025",
            "card_holder_name": "CL-BRW1"
        }
    },
    "billing": {
        "address": {
            "city": "Los Angeles",
            "country": "US",
            "line1": "123 Main St",
            "line2": "Apt 4B",
            "line3": null,
            "zip": "90001",
            "state": "CA",
            "first_name": "John",
            "last_name": "Doe",
            "origin_zip": null
        },
        "phone": null,
        "email": null
    },
    "auto_fulfill": false,
    "customer_id": "payout_customer11",
    "customer": {
        "id": "payout_customer11",
        "name": "John Doe",
        "email": "payout_customer@example.com",
        "phone": "999999999",
        "phone_country_code": "+65"
    },
    "client_secret": "payout_payout_gIUzolKdK7WVdkS7s8LN_secret_CVOMzeDt415fSksQ5v18",
    "return_url": null,
    "business_country": null,
    "business_label": null,
    "description": "Its my first payout request",
    "entity_type": "Individual",
    "recurring": true,
    "metadata": {},
    "merchant_connector_id": "mca_jX0wlGsB9NYD9FPIhagn",
    "status": "requires_fulfillment",
    "error_message": null,
    "error_code": null,
    "profile_id": "pro_Js7WcBCrnlkRkNQRA4YR",
    "created": "2025-12-11T11:19:54.993Z",
    "connector_transaction_id": null,
    "priority": null,
    "payout_link": null,
    "email": "payout_customer@example.com",
    "name": "John Doe",
    "phone": "999999999",
    "phone_country_code": "+65",
    "unified_code": null,
    "unified_message": null,
    "payout_method_id": null
}

```

Void (worldpayxml):

```

{
    "payout_id": "payout_gIUzolKdK7WVdkS7s8LN",
    "merchant_id": "merchant_1765451766",
    "merchant_order_reference_id": null,
    "amount": 100,
    "currency": "GBP",
    "connector": "worldpayxml",
    "payout_type": "card",
    "payout_method_data": {
        "card": {
            "card_issuer": null,
            "card_network": "Visa",
            "card_type": null,
            "card_issuing_country": null,
            "bank_code": null,
            "last4": "1111",
            "card_isin": "444433",
            "card_extended_bin": null,
            "card_exp_month": "12",
            "card_exp_year": "2025",
            "card_holder_name": "CL-BRW1"
        }
    },
    "billing": {
        "address": {
            "city": "Los Angeles",
            "country": "US",
            "line1": "123 Main St",
            "line2": "Apt 4B",
            "line3": null,
            "zip": "90001",
            "state": "CA",
            "first_name": "John",
            "last_name": "Doe",
            "origin_zip": null
        },
        "phone": null,
        "email": null
    },
    "auto_fulfill": false,
    "customer_id": "payout_customer11",
    "customer": {
        "id": "payout_customer11",
        "name": "John Doe",
        "email": "payout_customer@example.com",
        "phone": "999999999",
        "phone_country_code": "+65"
    },
    "client_secret": "payout_payout_gIUzolKdK7WVdkS7s8LN_secret_CVOMzeDt415fSksQ5v18",
    "return_url": null,
    "business_country": null,
    "business_label": null,
    "description": "Its my first payout request",
    "entity_type": "Individual",
    "recurring": true,
    "metadata": {},
    "merchant_connector_id": "mca_jX0wlGsB9NYD9FPIhagn",
    "status": "cancelled",
    "error_message": "Cancelled by user",
    "error_code": null,
    "profile_id": "pro_Js7WcBCrnlkRkNQRA4YR",
    "created": "2025-12-11T11:19:54.993Z",
    "connector_transaction_id": null,
    "priority": null,
    "payout_link": null,
    "email": "payout_customer@example.com",
    "name": "John Doe",
    "phone": "999999999",
    "phone_country_code": "+65",
    "unified_code": null,
    "unified_message": null,
    "payout_method_id": null
}

```

create+confirm (paypal):

Request:

```

{
    "amount": 1,
    "currency": "EUR",
    "customer_id": "payout_customer",
    "email": "payout_customer@example.com",
    "name": "John Doe",
    "phone": "999999999",
    "phone_country_code": "+65",
    "description": "Its my first payout request",
    "payout_type": "wallet",
    "payout_method_data": {
        "wallet": {
            "paypal": {
                "email": "sk.sakil@juspay.in"
            }
        }
    },
    "billing": {
        "address": {
            "line1": "1467",
            "line2": "Harrison Street",
            "line3": "Harrison Street",
            "city": "San Fransico",
            "state": "NY",
            "zip": "94122",
            "country": "US",
            "first_name": "John",
            "last_name": "Doe"
        },
        "phone": {
            "number": "8056594427",
            "country_code": "+91"
        }
    },
    "entity_type": "NaturalPerson",
    "recurring": false,
    "metadata": {
        "ref": "123"
    },
    "routing": {
        "type": "single",
        "data": "paypal"
    },
    "confirm": true,
    "auto_fulfill": false
}

```

Response:

```

{
    "payout_id": "payout_Cq70YRwz5skDuuPTWhpr",
    "merchant_id": "merchant_1765453144",
    "merchant_order_reference_id": null,
    "amount": 1,
    "currency": "EUR",
    "connector": "paypal",
    "payout_type": "wallet",
    "payout_method_data": {
        "wallet": {
            "field_type": "email",
            "email": "sk******@juspay.in"
        }
    },
    "billing": {
        "address": {
            "city": "San Fransico",
            "country": "US",
            "line1": "1467",
            "line2": "Harrison Street",
            "line3": "Harrison Street",
            "zip": "94122",
            "state": "NY",
            "first_name": "John",
            "last_name": "Doe",
            "origin_zip": null
        },
        "phone": {
            "number": "8056594427",
            "country_code": "+91"
        },
        "email": null
    },
    "auto_fulfill": false,
    "customer_id": "payout_customer",
    "customer": {
        "id": "payout_customer",
        "name": "John Doe",
        "email": "payout_customer@example.com",
        "phone": "999999999",
        "phone_country_code": "+65"
    },
    "client_secret": "payout_payout_Cq70YRwz5skDuuPTWhpr_secret_ZCCele9hZA6BMQ8CHY25",
    "return_url": null,
    "business_country": null,
    "business_label": null,
    "description": "Its my first payout request",
    "entity_type": "NaturalPerson",
    "recurring": false,
    "metadata": {
        "ref": "123"
    },
    "merchant_connector_id": "mca_ApD066ESuAYMaB0oG2nR",
    "status": "requires_fulfillment",
    "error_message": null,
    "error_code": null,
    "profile_id": "pro_exQMYMbRkK1AkTPgXPp4",
    "created": "2025-12-11T11:53:21.724Z",
    "connector_transaction_id": null,
    "priority": null,
    "payout_link": null,
    "email": "payout_customer@example.com",
    "name": "John Doe",
    "phone": "999999999",
    "phone_country_code": "+65",
    "unified_code": null,
    "unified_message": null,
    "payout_method_id": null
}

```

Void:

```

{
    "payout_id": "payout_Cq70YRwz5skDuuPTWhpr",
    "merchant_id": "merchant_1765453144",
    "merchant_order_reference_id": null,
    "amount": 1,
    "currency": "EUR",
    "connector": "paypal",
    "payout_type": "wallet",
    "payout_method_data": {
        "wallet": {
            "field_type": "email",
            "email": "sk******@juspay.in"
        }
    },
    "billing": {
        "address": {
            "city": "San Fransico",
            "country": "US",
            "line1": "1467",
            "line2": "Harrison Street",
            "line3": "Harrison Street",
            "zip": "94122",
            "state": "NY",
            "first_name": "John",
            "last_name": "Doe",
            "origin_zip": null
        },
        "phone": {
            "number": "8056594427",
            "country_code": "+91"
        },
        "email": null
    },
    "auto_fulfill": false,
    "customer_id": "payout_customer",
    "customer": {
        "id": "payout_customer",
        "name": "John Doe",
        "email": "payout_customer@example.com",
        "phone": "999999999",
        "phone_country_code": "+65"
    },
    "client_secret": "payout_payout_Cq70YRwz5skDuuPTWhpr_secret_ZCCele9hZA6BMQ8CHY25",
    "return_url": null,
    "business_country": null,
    "business_label": null,
    "description": "Its my first payout request",
    "entity_type": "NaturalPerson",
    "recurring": false,
    "metadata": {
        "ref": "123"
    },
    "merchant_connector_id": "mca_ApD066ESuAYMaB0oG2nR",
    "status": "cancelled",
    "error_message": "Cancelled by user",
    "error_code": null,
    "profile_id": "pro_exQMYMbRkK1AkTPgXPp4",
    "created": "2025-12-11T11:53:21.724Z",
    "connector_transaction_id": null,
    "priority": null,
    "payout_link": null,
    "email": "payout_customer@example.com",
    "name": "John Doe",
    "phone": "999999999",
    "phone_country_code": "+65",
    "unified_code": null,
    "unified_message": null,
    "payout_method_id": null
}

```

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

### CODE REVIEW

**Review by Sakilmostak — APPROVED** [review]

File: crates/common_utils/src/payout_method_utils.rs [hunk 1]
```diff
@@ -206,31 +206,39 @@ pub struct PixBankTransferAdditionalData {
...
 }
 
 /// Masked payout method details for paypal wallet payout method
 #[derive(
-    Default, Eq, PartialEq, Clone, Debug, Deserialize, Serialize, FromSqlRow, AsExpression, ToSchema,
+    Eq, PartialEq, Clone, Debug, Deserialize, Serialize, FromSqlRow, AsExpression, ToSchema,
 )]
 #[diesel(sql_type = Jsonb)]
-pub struct PaypalAdditionalData {
+#[serde(tag = "flow_type", rename_all = "snake_case")]
```
Comment (Sakilmostak) [inline crates/common_utils/src/payout_method_utils.rs]: change the tag to 'field_type'

**Review by Sakilmostak — CHANGES_REQUESTED** [review]
otherwise looks good to me

**Review by Sakilmostak — DISMISSED** [review]

File: crates/api_models/src/payouts.rs [hunk 2]
```diff
@@ -1050,11 +1050,22 @@ impl From<Wallet> for payout_method_utils::WalletAdditionalData {
...
                 telephone_number,
                 paypal_id,
-            }) => Self::Paypal(Box::new(payout_method_utils::PaypalAdditionalData {
-                email: email.map(ForeignFrom::foreign_from),
-                telephone_number: telephone_number.map(From::from),
-                paypal_id: paypal_id.map(From::from),
-            })),
+            }) => {
+                let paypal_additional_data = if let Some(e) = email {
+                    payout_method_utils::PaypalAdditionalData::Email {
```
Comment (sai-harsha-vardhan) [inline crates/api_models/src/payouts.rs:1248]: Why are we sending only either of these data, it's possible to have values for multiple at a time right?

Comment (Vani-1107) [reply crates/api_models/src/payouts.rs:1248]: For payouts via Paypal, it is always expected that exactly one of the three fields would be present.

File: crates/router/src/core/payouts.rs [hunk 3]
```diff
@@ -575,7 +581,13 @@ pub async fn payouts_cancel_core(
         }));
 
     // Make local cancellation
-    } else if helpers::is_eligible_for_local_payout_cancellation(status) {
+    } else if helpers::is_eligible_for_local_payout_cancellation(status)
+        && (connector_name.is_none()
```
Comment (sai-harsha-vardhan) [inline crates/router/src/core/payouts.rs]: nit: `connector_name.is_none()` check is not needed if we are unwrapping to false if it's None

Comment (Vani-1107) [reply crates/router/src/core/payouts.rs]: Hi @sai-harsha-vardhan ,
This condition is intended to allow local payout cancellation when the payout status is eligible, and either:
- we donot have a connector yet, or
- a connector is present and it supports instant payouts

```
else if helpers::is_eligible_for_local_payout_cancellation(status)
        && (connector_name.is_none()
                || connector_name
                .as_ref()
                .map(|name| name.supports_instant_payout(payout_data.payouts.payout_type))
                .unwrap_or(false))

```

**Review by Sakilmostak — APPROVED** [review]

**Review by sai-harsha-vardhan — APPROVED** [review]
