### PR TITLE
fix(api_key): fix api key `list` and `update` endpoints for v2

### LINKED ISSUE #5979: [REFACTOR] API Key List and Update endpoints in Hyperswitch V2
Update API Key endpoint in V2, the URLs are registered in the `app.rs` but the necessary changes to it has not been made in `api_keys.rs`.

In addition to that, List API Key endpoint for V2 does not work as no such thing exist in `api_keys.rs`.

So at present, when that endpoint is hit, you'll receive a 404 as mentioned below:

```curl
curl --location --request PUT '{{baseUrl}}/v2/api_keys/{{api_key_id}}' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'x-merchant-id: {{mechant_id}}' \
--header 'api-key: {{admin_api_key}}' \
--data '{
     "name": "My new Api Key"
}'
```
```json
wrong number of parameters: 1 expected 2
```

List end point:

```curl
curl --location '{{baseUrl}}/v2/api_keys/list' \
--header 'x-merchant-id: {{mechant_id}}' \
--header 'api-key: {{admin_api_key}}'
```
```json
wrong number of parameters: 0 expected 1
```

I'll be fixing this.

### PR DESCRIPTION
**Pull request by pixincreate**
## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

This PR fixes `404` errors thrown by API Key List and Update endpoints.

Previously:

Update end point:

```curl
curl --location --request PUT '{{baseUrl}}/v2/api_keys/{{api_key_id}}' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'x-merchant-id: {{mechant_id}}' \
--header 'api-key: {{admin_api_key}}' \
--data '{
     "name": "My new Api Key"
}'
```
```json
wrong number of parameters: 1 expected 2
```

List end point:

```curl
curl --location '{{baseUrl}}/v2/api_keys/list' \
--header 'x-merchant-id: {{mechant_id}}' \
--header 'api-key: {{admin_api_key}}'
```
```json
wrong number of parameters: 0 expected 1
```

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

endpoints under `v2` flags were not properly handled in `api_keys.rs` file and this PR fixes that.

closes #5979

## How did you test it?

tested it by running locally.

Create Api Key endpoint:

```curl
curl --location 'http://Localhost:8080/v2/api_keys' \
--header 'x-merchant-id: cloth_seller_o6pEetqmlQjhp0kfR7ae' \
--header 'Content-Type: application/json' \
--header 'api-key: test_admin' \
--data '{
    "name": "My Api Key",
    "expiration": "never"
}'
```
```json
{
    "key_id": "dev_xhm09vaThZEPcxuZMJOG",
    "merchant_id": "cloth_seller_o6pEetqmlQjhp0kfR7ae",
    "name": "My Api Key",
    "description": null,
    "api_key": "dev_N0jTf3lRHljowpMGs9IKTPhOYkZXY3Sca8kUpSR5DbtjxaBvfqMIqshU5hx81AJp",
    "created": "2024-09-20T13:03:00.859Z",
    "expiration": "never"
}
```

Update Api Key endpoint:

```curl
curl --location --request PUT 'http://Localhost:8080/v2/api_keys/dev_xhm09vaThZEPcxuZMJOG' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'x-merchant-id: cloth_seller_o6pEetqmlQjhp0kfR7ae' \
--header 'api-key: test_admin' \
--data '{
     "name": "My new Api Key"
}'
```
```json
{
    "key_id": "dev_xhm09vaThZEPcxuZMJOG",
    "merchant_id": "cloth_seller_o6pEetqmlQjhp0kfR7ae",
    "name": "My new Api Key",
    "description": null,
    "prefix": "dev_N0jTf3lR",
    "created": "2024-09-20T13:03:00.859Z",
    "expiration": "never"
}
```

List Api Keys endpoint:

```curl
curl --location 'http://Localhost:8080/v2/api_keys/list' \
--header 'x-merchant-id: cloth_seller_o6pEetqmlQjhp0kfR7ae' \
--header 'api-key: test_admin'
```
```json
[
    {
        "key_id": "dev_X8F7qFGnO9a1IGIrtuzb",
        "merchant_id": "cloth_seller_o6pEetqmlQjhp0kfR7ae",
        "name": "My Api Key",
        "description": null,
        "prefix": "dev_8jfmSMnn",
        "created": "2024-09-20T13:02:57.150Z",
        "expiration": "never"
    },
    {
        "key_id": "dev_F8TDC9bHerHzYdiql80m",
        "merchant_id": "cloth_seller_o6pEetqmlQjhp0kfR7ae",
        "name": "My Api Key",
        "description": null,
        "prefix": "dev_g8SO3blK",
        "created": "2024-09-20T13:02:57.815Z",
        "expiration": "never"
    },
    {
        "key_id": "dev_DQ3C3DdFczazUFNc6n0i",
        "merchant_id": "cloth_seller_o6pEetqmlQjhp0kfR7ae",
        "name": "My Api Key",
        "description": null,
        "prefix": "dev_GnLRtXQm",
        "created": "2024-09-20T13:02:58.361Z",
        "expiration": "never"
    },
    {
        "key_id": "dev_kdISpxDQBmMpJ8BQuGmH",
        "merchant_id": "cloth_seller_o6pEetqmlQjhp0kfR7ae",
        "name": "My Api Key",
        "description": null,
        "prefix": "dev_h34nUAh4",
        "created": "2024-09-20T13:02:58.796Z",
        "expiration": "never"
    },
    {
        "key_id": "dev_WBHT3v4SlWcU4R3R8Wt2",
        "merchant_id": "cloth_seller_o6pEetqmlQjhp0kfR7ae",
        "name": "My Api Key",
        "description": null,
        "prefix": "dev_v5jdBEFo",
        "created": "2024-09-20T13:02:59.806Z",
        "expiration": "never"
    },
    {
        "key_id": "dev_qiwCmtE8Lbj24uJYC1wQ",
        "merchant_id": "cloth_seller_o6pEetqmlQjhp0kfR7ae",
        "name": "My Api Key",
        "description": null,
        "prefix": "dev_WRaLVEGq",
        "created": "2024-09-20T13:03:00.335Z",
        "expiration": "never"
    },
    {
        "key_id": "dev_xhm09vaThZEPcxuZMJOG",
        "merchant_id": "cloth_seller_o6pEetqmlQjhp0kfR7ae",
        "name": "My new Api Key",
        "description": null,
        "prefix": "dev_N0jTf3lR",
        "created": "2024-09-20T13:03:00.859Z",
        "expiration": "never"
    }
]
```

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

### CODE REVIEW

File: crates/router/src/routes/api_keys.rs [hunk 1]
```diff
@@ -335,3 +337,34 @@ pub async fn api_key_list(
...
+    let payload = query.into_inner();
+
+    api::server_wrap(
+        flow,
+        state,
+        &req,
+        (payload.limit, payload.skip),
+        |state, authentication_data, (limit, offset), _| async move {
+            let merchant_id = authentication_data.merchant_account.get_id().to_owned();
+            api_keys::list_api_keys(state, merchant_id, limit, offset).await
```
Comment (SanchithHegde) [inline crates/router/src/routes/api_keys.rs:357]: You can directly pass `payload` here.
```suggestion
        payload,
        |state, authentication_data, payload, _| async move {
            let merchant_id = authentication_data.merchant_account.get_id().to_owned();
            api_keys::list_api_keys(state, merchant_id, payload.limit, payload.skip).await
```

File: crates/common_utils/src/events.rs [hunk 2]
```diff
@@ -130,6 +130,7 @@ impl_api_event_type!(
         (&String, &String),
         (Option<i64>, Option<i64>, String),
         (Option<i64>, Option<i64>, id_type::MerchantId),
+        (Option<i64>, Option<i64>),
```
Comment (SanchithHegde) [inline crates/common_utils/src/events.rs:133]: Once the other change is made, you can remove this line. 
And implement the `Miscellaneous` API event type for `ListApiKeyConstraints` instead.

File: crates/router/src/routes/api_keys.rs [hunk 3]
```diff
@@ -283,24 +284,10 @@ pub async fn api_key_revoke(
     .await
 }
 
+#[cfg(feature = "v1")]
 /// API Key - List
 ///
 /// List all API Keys associated with your merchant account.
```
Comment (SanchithHegde) [inline crates/router/src/routes/api_keys.rs:290]: You can remove these doc comments as well.
You can remove the doc comments for other functions in this file as well.

File: crates/openapi/src/routes/api_keys.rs [hunk 4]
```diff
@@ -163,3 +163,44 @@ pub async fn api_key_revoke() {}
...
+        ("skip" = Option<i64>, Query, description = "The number of API Keys to skip when retrieving the list of API keys."),
+    ),
+    responses(
+        (status = 200, description = "List of API Keys retrieved successfully", body = Vec<RetrieveApiKeyResponse>),
+    ),
+    tag = "API Key",
+    operation_id = "List all API Keys associated with a merchant account",
+    security(("admin_api_key" = []))
+)]
+pub async fn api_key_list() {}
```
Comment (SanchithHegde) [inline crates/openapi/src/routes/api_keys.rs:206]: @Narayanbhat166 @jarnura Should this endpoint be included in this file or in the merchant account file?

@pixincreate Could you register this endpoint in `crates/openapi/src/openapi.rs` and `crates/openapi/src/openapi_v2.rs`, and make suitable changes to the Mintlify API reference (`api-reference` and `api-reference-v2` directories)?

Comment (Narayanbhat166) [reply crates/openapi/src/routes/api_keys.rs:206]: > Should this endpoint be included in this file or in the merchant account file

@SanchithHegde We do not have the `merchant_id` in path. So this can be registered here.

File: crates/router/src/routes/api_keys.rs [hunk 5]
```diff
@@ -190,26 +177,27 @@ pub async fn api_key_update(
 pub async fn api_key_update(
     state: web::Data<AppState>,
     req: HttpRequest,
-    path: web::Path<(common_utils::id_type::MerchantId, String)>,
```
Comment (Narayanbhat166) [inline crates/router/src/routes/api_keys.rs:193]: can you update this in openapi also for v2?

Comment (pixincreate) [reply crates/router/src/routes/api_keys.rs:193]: this was updated by you on august 28, 2024 in #5709([api_keys.rs](https://github.com/juspay/hyperswitch/pull/5709/files#diff-7c85aea5f3131c88211bf2b89db7c0dda2aa73ab584ced6cf6f57ff793cec541))

**Review by Narayanbhat166 — APPROVED** [review]

**Review by SanchithHegde — APPROVED** [review]

**Review by lsampras — APPROVED** [review]

**Review by ShivanshMathurJuspay — APPROVED** [review]
