### PR TITLE
fix(admin): Add JWT Auth for Org Read and Update APIs

### LINKED ISSUE #6141: fix(admin): jwt added for organization update and retrieve
Previously, updating and retrieving organization details required authentication using the admin API key. With the recent change, the dashboard JWT can now be used to update the org_name directly through the dashboard.

### PR DESCRIPTION
**Pull request by Riddhiagrawal001**
## Type of Change

- [X] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Previously, updating and retrieving organization details required authentication using the admin API key. With the recent change, the dashboard JWT can now be used to update the org_name directly through the dashboard.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

Closes #6141

## How did you test it?

Request : 
```
curl --location --request PUT 'http://localhost:8080/organization/${org_id}' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer JWT' \
--data '{
    "organization_name":"RiddhiTest3"
}'
```

Response:
```
{
    "organization_id": "org_id",
    "organization_name": "RiddhiTest3",
    "organization_details": null,
    "metadata": null,
    "modified_at": "2024-09-27 07:13:13.074956",
    "created_at": "2024-09-19 12:46:25.990045"
}
```

Request :
```
curl --location 'http://localhost:8080/organization/${org_id}' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer JWT' \
--data ''
```

Response:
```
{
    "organization_id": "org_id",
    "organization_name": "RiddhiTest3",
    "organization_details": null,
    "metadata": null,
    "modified_at": "2024-09-27 07:13:13.074956",
    "created_at": "2024-09-19 12:46:25.990045"
}
```
## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

### CODE REVIEW

File: crates/router/src/routes/admin.rs [hunk 1]
```diff
@@ -39,14 +39,24 @@ pub async fn organization_update(
...
         state,
         &req,
         json_payload.into_inner(),
         |state, _, req, _| update_organization(state, org_id.clone(), req),
-        &auth::AdminApiAuth,
+        auth::auth_type(
+            &auth::AdminApiAuth,
+            &auth::JWTAuthOrganizationFromRoute {
+                organization_id,
+                required_permission: Permission::MerchantAccountRead,
```
Comment (apoorvdixit88) [inline crates/router/src/routes/admin.rs:55]: evaluate the permission
```suggestion
                required_permission: Permission::MerchantAccountWrite,
```

**Review by racnan — APPROVED** [review]

**Review by ThisIsMani — APPROVED** [review]

**Review by lsampras — APPROVED** [review]
