### PR TITLE
fix(user): blacklist token after delete user role

### LINKED ISSUE #4427: Blacking token after delete user role
Even after deleting the user role, the logged in user is able to perform the JWT operations. Hence these need to be prohibited by adding the token in blacklist.

### PR DESCRIPTION
**Pull request by apoorvdixit88**
## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
The PR add support to blocklist JWT token of the deleted user/user role. After delete signined user won't be able to perform any operation as token is blocklisted.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context
closes #4427 

## How did you test it?
SignIn/Signup
```
curl --location 'http://localhost:8080/user/signup' \
--header 'Content-Type: application/json' \
--header 'api-key: test_admin' \
--data-raw '{
    "email": "test1@gmail.com",
    "password": "t"
}'
```

Invite another user
```
curl --location 'http://localhost:8080/user/user/invite' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer JWT' \
--data-raw '{
    "email": "test3@gmail.com",
    "name": "test3",
    "role_id": "merchant_view_only"
}'
```

Sign in to this new user account and perform some operations JWT based, like listing payments etc.

Sing in  again into account from which this user was invited.

Delete this new user
```
curl --location --request DELETE 'http://localhost:8080/user/user/delete' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer JWT' \
--data-raw '{
  "email": "test3@gmail.com"
}'
```
Response 200 Ok

Try performing same operations for the newly invited user now, it should give response:
```
{
    "error": {
        "type": "invalid_request",
        "message": "Access forbidden, invalid JWT token was used",
        "code": "IR_17"
    }
}
```
This means the previous token is blacklisted sucessfully.
## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

### CODE REVIEW

File: crates/router/src/core/user_role.rs [hunk 1]
```diff
@@ -312,6 +314,7 @@ pub async fn delete_user_role(
             .change_context(UserErrors::InternalServerError)
             .attach_printable("Error while deleting user role")?;
 
+        auth::blacklist::insert_user_in_blacklist(&state, &deleted_user_role.user_id).await?;
         Ok(ApplicationResponse::StatusOk)
```
Comment (racnan) [inline crates/router/src/core/user_role.rs:318]: repeated code, can be taken out of if else block.

File: crates/router/src/db/user_role.rs [hunk 2]
```diff
@@ -459,18 +460,22 @@ impl UserRoleInterface for MockDb {
...
-            .ok_or(errors::StorageError::ValueNotFound(format!(
-                "No user available for user_id = {user_id}"
-            )))?;
-        user_roles.remove(user_role_index);
-        Ok(true)
+            .position(|role| role.user_id == user_id && role.merchant_id == merchant_id)
+        {
+            Some(index) => {
+                let deleted_user_role = user_roles.remove(index);
+                Ok(deleted_user_role)
```
Comment (ThisIsMani) [inline crates/router/src/db/user_role.rs:472]: No need of assignment here as well.
```suggestion
Ok(user_roles.remove(index))
```

**Review by ThisIsMani — APPROVED** [review]

**Review by racnan — APPROVED** [review]
