### PR TITLE
ci(postman): hotfix for stripe and nmi collections failing

### LINKED ISSUE #3955: [BUG] [CI] NMI and Stripe CI failing
As we can see here in CI's commit, https://github.com/juspay/hyperswitch/commit/cd7040fa8cad2e69a53e3ed609c9eb8a8a17495a, it is clear that NMI and Stripe collection are the ones that are affected which again can be confirmed with https://github.com/juspay/hyperswitch/actions/runs/8148897592/job/22272607599

CI checks are failing.

### PR DESCRIPTION
**Pull request by pixincreate**
## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [x] CI/CD

## Description

This PR is a fix for postman CI failing due a bug introduced in https://github.com/juspay/hyperswitch/pull/3807.  

As we can see here in CI's commit, https://github.com/juspay/hyperswitch/commit/cd7040fa8cad2e69a53e3ed609c9eb8a8a17495a, it is clear that NMI and Stripe collection are the ones that are affected which again can be confirmed with https://github.com/juspay/hyperswitch/actions/runs/8148897592/job/22272607599

Closes #3955 

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

People are shouting that the collections are failing. We've to keep them calm.

## How did you test it?

NMI

image

Stripe

image

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

### CODE REVIEW

File: crates/test_utils/src/main.rs [hunk 1]
```diff
@@ -18,17 +18,20 @@ fn main() {
...
+    if !paths.is_empty() {
+        let git_status = Command::new("git").arg("restore").args(&paths).output();
+
+        match git_status {
+            Ok(output) => {
+                if !output.status.success() {
+                    let stderr_str = String::from_utf8_lossy(&output.stderr);
+                    eprintln!("Git command failed with error: {stderr_str}");
+                }
+            }
```
Comment (SanchithHegde) [inline crates/test_utils/src/main.rs:31]:
```suggestion
            Ok(output) if !output.status.success() => {
                let stderr_str = String::from_utf8_lossy(&output.stderr);
                eprintln!("Git command failed with error: {stderr_str}");
            }
```

**Review by Narayanbhat166 — APPROVED** [review]

**Review by likhinbopanna — APPROVED** [review]

**Review by SanchithHegde — APPROVED** [review]

**Comment by pixincreate** [comment]
Added to merge queue to get this PR merged before tomorrow's deployment just so that the CI do not fail.
