### PR TITLE
fix: script for one click docker setup

### LINKED ISSUE #7761: One click docker setup
A script is needed to ensure one click docker setup, to minimise issues faced by users.
> Run the whole setup with simple command
> Show output with localhost links for different setups

### PR DESCRIPTION
**Pull request by gorakhnathy7**
## Type of Change

- [ ] Bugfix
- [ ] New feature
- [X] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Added the script for showing output of  ```docker compose up -d``` command, along with links to access individual components.
### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

closes #7761 
## How did you test it?

Attached SS from testing in local.
Screenshot 2025-04-13 at 11 06 39 PM

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

### CODE REVIEW

File: scripts/docker_output.sh [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+
+MAX_RETRIES=70
+RETRY_COUNT=0
+
+# Wait until the service is available or retries are exhausted
+while ! curl --silent --fail "${SERVICE_URL}" > /dev/null; do
+    if (( RETRY_COUNT >= MAX_RETRIES )); then
+        echo ""
+        echo "Service failed to start. Kindly check the logs."
+        echo "You can view the logs using the command: docker-compose logs -f"
```
Comment (SanchithHegde) [inline scripts/docker_output.sh:17]:
```suggestion
        echo "You can view the logs using the command: docker-compose logs -f <service name>"
```

**Review by SanchithHegde — APPROVED** [review]
