### PR TITLE
fix: make AWS KMS key_id optional for flexible encryption workflows

### LINKED ISSUE #10276: Make AWS KMS key_id optional for flexible encryption/decryption workflows
## Problem Statement

The AWS KMS integration currently requires the `key_id` field to be mandatory in the configuration. However, AWS KMS supports decryption operations without explicitly providing a key ID, as the ciphertext metadata contains information about which key was used for encryption.

This inflexibility prevents certain use cases:
- Decrypting data that was encrypted with different KMS keys
- Working with ciphertexts where the key ID is embedded in the metadata
- Simplifying configurations where key rotation is involved

## Proposed Solution

Make the `key_id` field optional in `AwsKmsConfig` and `AwsKmsClient`:

### Decryption Behavior
- Allow decryption operations without providing a key ID
- KMS will automatically infer the key from the ciphertext metadata

### Encryption Behavior
- Continue to require key ID for encryption operations
- Return a clear error (`MissingKeyId`) if encryption is attempted without a key ID

### Backward Compatibility
- Maintain existing validation in the encryption management layer to ensure key_id is provided for encryption workflows
- No breaking changes to existing implementations

## Technical Details

**Files to be modified:**
- `crates/external_services/src/aws_kms/core.rs` - Core KMS client implementation
- `crates/external_services/src/managers/encryption_management.rs` - Encryption management validation

**Changes:**
1. Change `key_id: String` to `key_id: Option<String>` in structs
2. Conditionally set key_id in decrypt() method
3. Add validation for encryption operations
4. Add new error variant for missing key_id during encryption

## Benefits

- **Flexibility**: Support for multi-key decryption scenarios
- **AWS Best Practices**: Aligns with AWS KMS's built-in key inference capability
- **No Breaking Changes**: Existing encryption workflows continue to work as before
- **Better Error Handling**: Clear error messages when key_id is required but not provided

## Related

- #3184 - Relocate KMS decryptions into `kms.rs`
- #3250 - Enable runtime flag for `kms` feature

### PR DESCRIPTION
**Pull request by maverox**
## Summary

This PR makes the AWS KMS `key_id` field optional in the configuration to allow for more flexible encryption/decryption workflows. The key ID is now only required during encryption operations, while decryption can work without an explicit key ID when KMS can infer it from the ciphertext metadata.

**Closes #10276**

## Changes

- **`crates/external_services/src/aws_kms/core.rs`**:
  - Changed `key_id` field from `String` to `Option<String>` in both `AwsKmsConfig` and `AwsKmsClient` structs
  - Updated `decrypt()` method to conditionally set key_id only when provided
  - Updated `encrypt()` method to return an error (`MissingKeyId`) when key_id is not provided
  - Added new error variant `MissingKeyId` to handle cases where encryption is attempted without a key ID
  - Removed validation check for empty `key_id` in `AwsKmsConfig::validate()` since it's now optional

- **`crates/external_services/src/managers/encryption_management.rs`**:
  - Added validation check in `EncryptionManagementConfig::validate()` to ensure key_id is provided when using AWS KMS encryption management (maintains backward compatibility for the encryption management use case)

## Related Issues

- Closes #10276 - Make AWS KMS key_id optional for flexible encryption/decryption workflows
- Related to #3184 - Relocate KMS decryptions into `kms.rs`
- Related to #3250 - Enable runtime flag for `kms` feature

## Type of Change

- [x] Bug fix (addresses configuration flexibility)
- [x] Refactoring (improves code structure without changing behavior)
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation update

## Technical Context

AWS KMS supports decryption without an explicit key ID because the ciphertext metadata contains information about which key was used for encryption. This change allows:

1. **Decryption without key_id**: Useful when handling ciphertexts that were encrypted with different keys or when the key ID is embedded in the ciphertext
2. **Encryption still requires key_id**: Ensures encryption operations explicitly specify which key to use
3. **Backward compatibility**: The encryption management layer still validates that key_id is provided for encryption workflows

## Testing

- [x] Code changes follow the project's coding standards
- [x] Changes maintain backward compatibility for encryption management
- [ ] Manual testing of encryption/decryption workflows with and without key_id
- [ ] Integration tests to verify KMS operations work as expected

## Checklist

- [x] Code follows project style guidelines
- [x] Self-review completed
- [x] Error handling properly implemented
- [x] Changes are focused and minimal
- [ ] Tests pass locally
- [ ] Documentation updated if needed

### CODE REVIEW

File: crates/external_services/src/aws_kms/core.rs [hunk 1]
```diff
@@ -88,10 +91,15 @@ impl AwsKmsClient {
         let start = Instant::now();
         let plaintext_blob = Blob::new(data.as_ref());
 
-        let encrypted_output = self
-            .inner_client
-            .encrypt()
-            .key_id(&self.key_id)
+        let mut encryption_builder = self.inner_client.encrypt();
```
Comment (hrithikesh026) [inline crates/external_services/src/aws_kms/core.rs:94]: I was wondering if we even need an `encrypt` interface function. I believe application has no use case for encrypting using AWS KMS. @SanchithHegde
