### PR TITLE
fix: script for one click docker setup

### LINKED ISSUE #7761: One click docker setup
A script is needed to ensure one click docker setup, to minimise issues faced by users.
> Run the whole setup with simple command
> Show output with localhost links for different setups

### PR DESCRIPTION
**Pull request by gorakhnathy7**
## Type of Change

- [ ] Bugfix
- [ ] New feature
- [X] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Script for one click docker setup, to minimise issues faced by users.

>Run the whole setup with simple command
>Show output with localhost links for different setups

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

Script for one click docker setup, to minimise issues faced by users.
Closes #7761 

## How did you test it?

Attaching ss of test on local.
Screenshot 2025-04-08 at 4 12 13 PM

## Checklist

- [ ] I formatted the code `cargo +nightly fmt --all`
- [ ] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

### CODE REVIEW

File: scripts/docker_output.sh [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+LIGHT_SKY_BLUE="\033[38;2;135;206;250m"
+RESET="\033[0m"
+
+# Print the service URLs with only the links colored
+echo -e "Control Centre running at ${LIGHT_SKY_BLUE}http://localhost:9000${RESET}"
+echo -e "App server running at ${LIGHT_SKY_BLUE}http://localhost:8080/health${RESET}"
+echo -e "Web-SDK running at ${LIGHT_SKY_BLUE}http://localhost:5252/HyperLoader.js${RESET}"
+echo -e "Mailhog running at ${LIGHT_SKY_BLUE}http://localhost:8025${RESET}"
+echo -e "PostgreSQL running at ${LIGHT_SKY_BLUE}localhost:5432${RESET} (no web interface)"
+echo -e "Redis running at ${LIGHT_SKY_BLUE}localhost:6379${RESET} (no web interface)"
```
[the remark this answers is not in the document]
Comment (gorakhnathy7) [reply scripts/docker_output.sh:27]: Removed for now.

File: scripts/docker_output.sh [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+
+echo ""
+
+# Define ANSI 24-bit (true color) escape sequences for Light Sky Blue
+LIGHT_SKY_BLUE="\033[38;2;135;206;250m"
+RESET="\033[0m"
+
+# Print the service URLs with only the links colored
+echo -e "Control Centre running at ${LIGHT_SKY_BLUE}http://localhost:9000${RESET}"
+echo -e "App server running at ${LIGHT_SKY_BLUE}http://localhost:8080/health${RESET}"
```
[the remark this answers is not in the document]
Comment (gorakhnathy7) [reply scripts/docker_output.sh:23]: Sure, corrected.

File: scripts/docker_output.sh (hunk 1 above)
[the remark this answers is not in the document]
Comment (gorakhnathy7) [reply scripts/docker_output.sh:27]: Keeping the mailhog one for now, as it is still something that user can hit and see the response.

File: README.md [hunk 3]
```diff
@@ -78,37 +78,19 @@ Read more at [Hyperswitch docs](https://docs.hyperswitch.io/).
 ### 1. Local Setup
 
 You can run Hyperswitch on your system using Docker compose after cloning this repository. 
+We recommend using Docker Desktop for Windows and Mac OS (Or Orbstack). On Linux, you can install Docker Engine directly.
 
 ```shell
 git clone --depth 1 --branch latest https://github.com/juspay/hyperswitch
 cd hyperswitch
 docker compose up -d
+./scripts/docker_output.sh
```
Comment (SanchithHegde) [inline README.md:87]: Nit:

```suggestion
scripts/docker_output.sh
```

Can you run `chmod +x scripts/docker_output.sh` and then commit the file?

File: scripts/docker_output.sh [hunk 4]
```diff
@@ -0,0 +1,25 @@
...
+# Define the URL to check service availability (adjust HOST and PORT if needed)
+HOST="localhost"
+PORT="8080"
+SERVICE_URL="http://${HOST}:${PORT}/health"
+
+# Wait until the service is available
+while ! curl --silent --fail "${SERVICE_URL}" > /dev/null; do
+    printf "."
+    sleep 2
+done
```
Comment (SanchithHegde) [inline scripts/docker_output.sh:13]: This would wait indefinitely for the server to come up? What if the server failed to start due to some issue, say, port already in use, database couldn't be spin up, etc.?

Can we have a maximum number of retries, or maximum time duration for which retries would be done, at least?

Comment (gorakhnathy7) [reply scripts/docker_output.sh:13]: Corrected

File: scripts/docker_output.sh [hunk 5]
```diff
@@ -0,0 +1,33 @@
...
+
+MAX_RETRIES=70
+RETRY_COUNT=0
+
+# Wait until the service is available or retries are exhausted
+while ! curl --silent --fail "${SERVICE_URL}" > /dev/null; do
+    if (( RETRY_COUNT >= MAX_RETRIES )); then
+        echo ""
+        echo "Service failed to start. Kindly check the logs."
+        echo "You can view the logs using the command: docker-compose logs -f"
```
Comment (SanchithHegde) [inline scripts/docker_output.sh:17]:
```suggestion
        echo "You can view the logs using the command: docker-compose logs -f <service name>"
```

**Review by SanchithHegde — APPROVED** [review]

**Review by apoorvdixit88 — APPROVED** [review]
