### PR TITLE
fix(cypress): simplify error message for declined card status

### LINKED ISSUE #10416: Cypress Test Failing due to Change in message
Cypress Test are failing due to change in error message sturcture.

### PR DESCRIPTION
**Pull request by ayush22667**
## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Fix cypress tests.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

closes #10416

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

### CODE REVIEW

**Comment by likhinbopanna** [comment]
@ayush22667 Could you fix cybersource as well , even that is failing

File: cypress-tests/cypress/e2e/configs/Payment/Cybersource.js [hunk 1]
```diff
@@ -322,7 +322,7 @@ export const connectorDetails = {
         body: {
           status: "failed",
           error_message:
-            "Declined - One or more fields in the request contains invalid data, detailed_error_information: orderInformation.billTo.administrativeArea : INVALID_DATA",
+            "Declined - One or more fields in the request contains invalid data",
```
Comment (Gnanasundari24) [inline cypress-tests/cypress/e2e/configs/Payment/Cybersource.js:325]: WHy the detailed info got removed?

Comment (Gnanasundari24) [reply cypress-tests/cypress/e2e/configs/Payment/Cybersource.js:325]: Then from where we will get the detailed error?

Comment (ayush22667) [reply cypress-tests/cypress/e2e/configs/Payment/Cybersource.js:325]: This is done for getting consistency in gsm table for message field, we are storing detailed error information in error reason field.
