### PR TITLE
fix(router): merchant account delete does not delete the merchant_key_store

### LINKED ISSUE #2154: [BUG] merchant account delete does not delete the `merchant_key_store`
### Bug Description

When a merchant is created a `merchant_key_store` is created, which goes along with the `merchant_account`. But when the merchant account is deleted, the key store is not deleted. 

### Expected Behavior

Both merchant account and key store should be delted.

### Actual Behavior

The key store still exists. 

### Steps To Reproduce

- Create a merchant account.
- Delete the merchant account.

### Context For The Bug

_No response_

### Environment

Local

### Have you spent some time checking if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

No, but I'm happy to collaborate on a PR with someone else

### PR DESCRIPTION
**Pull request by dalprahcd**
## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Closes #2154 by calling `delete_merchant_key_store_by_merchant_id` at `merchant_account_delete`

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

### CODE REVIEW

File: crates/router/src/core/admin.rs [hunk 1]
```diff
@@ -470,6 +470,10 @@ pub async fn merchant_account_delete(
         .delete_merchant_account_by_merchant_id(&merchant_id)
         .await
         .to_not_found_response(errors::ApiErrorResponse::MerchantAccountNotFound)?;
+    let _is_deleted = db
+        .delete_merchant_key_store_by_merchant_id(&merchant_id)
+        .await
+        .to_not_found_response(errors::ApiErrorResponse::MerchantAccountNotFound)?;
```
Comment (dalprahcd) [inline crates/router/src/core/admin.rs:476]: I was not sure how to use `_is_deleted` and if I should delete the `merchant_key_store` after or before deleting the `merchant_account`

File: crates/router/src/db/merchant_key_store.rs [hunk 2]
```diff
@@ -90,6 +96,39 @@ impl MerchantKeyStoreInterface for Store {
...
+            let key_store_cache_key = format!("merchant_key_store_{}", merchant_id);
+            super::cache::get_or_populate_in_memory(
+                self,
+                &key_store_cache_key,
+                delete_func,
+                &ACCOUNTS_CACHE,
+            )
+            .await
+        }
+    }
```
Comment (dracarys18) [inline crates/router/src/db/merchant_key_store.rs:131]: Call `publish_and_redact` function here.

File: crates/router/src/core/admin.rs (hunk 1 above)
Comment (dracarys18) [reply crates/router/src/core/admin.rs:476]: Probably You can do 
```rust
   let is_merchant_account_deleted = db
        .delete_merchant_account_by_merchant_id(&merchant_id)
        .await
        .to_not_found_response(errors::ApiErrorResponse::MerchantAccountNotFound)?;
    let is_merchant_key_store_deleted = db
        .delete_merchant_key_store_by_merchant_id(&merchant_id)
        .await
        .to_not_found_response(errors::ApiErrorResponse::MerchantKeyStoreNotFound)?;
   
   return is_merchant_account_deleted && is_merchant_key_store_deleted
```

**Review by dracarys18 — CHANGES_REQUESTED** [review]

File: crates/router/src/core/admin.rs (hunk 1 above)
Comment (dalprahcd) [reply crates/router/src/core/admin.rs:476]: `errors::ApiErrorResponse::MerchantKeyStoreNotFound` does not exist, how to proceed? Should I implement?

Comment (dracarys18) [reply crates/router/src/core/admin.rs:476]: Please create it in the ApiResponse

File: crates/router/src/db/merchant_key_store.rs (hunk 2 above)
Comment (dalprahcd) [reply crates/router/src/db/merchant_key_store.rs]: Done.

File: crates/router/src/core/admin.rs (hunk 1 above)
Comment (dalprahcd) [reply crates/router/src/core/admin.rs]: Done.

File: crates/router/src/db/merchant_key_store.rs [hunk 3]
```diff
@@ -90,6 +97,37 @@ impl MerchantKeyStoreInterface for Store {
...
+        #[cfg(not(feature = "accounts_cache"))]
+        {
+            delete_func().await
+        }
+
+        #[cfg(feature = "accounts_cache")]
+        {
+            super::cache::publish_and_redact(
+                self,
+                CacheKind::Accounts(merchant_id.into()),
```
Comment (dracarys18) [inline crates/router/src/db/merchant_key_store.rs:125]: This should be `format!("merchant_key_store_{}", merchant_id)`

**Review by dracarys18 — CHANGES_REQUESTED** [review]

File: crates/router/src/db/merchant_key_store.rs (hunk 3 above)
Comment (dalprahcd) [reply crates/router/src/db/merchant_key_store.rs]: Changed to `let key_store_cache_key = format!("merchant_key_store_{}", merchant_id);`

File: crates/router/src/db/merchant_key_store.rs [hunk 4]
```diff
@@ -1,5 +1,6 @@
 use error_stack::{IntoReport, ResultExt};
 use masking::Secret;
+use storage_impl::redis::cache::CacheKind;
```
Comment (dracarys18) [inline crates/router/src/db/merchant_key_store.rs:3]: Add this under the feature flag         
```rust 
#[cfg(feature = "accounts_cache")]
```

**Review by dracarys18 — CHANGES_REQUESTED** [review]

File: crates/router/src/core/admin.rs [hunk 5]
```diff
@@ -466,13 +466,17 @@ pub async fn merchant_account_delete(
...
     let db = state.store.as_ref();
-    let is_deleted = db
+    let is_merchant_account_deleted = db
         .delete_merchant_account_by_merchant_id(&merchant_id)
         .await
         .to_not_found_response(errors::ApiErrorResponse::MerchantAccountNotFound)?;
+    let is_merchant_key_store_deleted = db
+        .delete_merchant_key_store_by_merchant_id(&merchant_id)
+        .await
+        .to_not_found_response(errors::ApiErrorResponse::MerchantAccountNotFound)?;
```
Comment (Narayanbhat166) [inline crates/router/src/core/admin.rs:476]: Better to perform this operation only if the merchant account was deleted, you can have a condition here as to 
```rust
if is_merchant_account_deleted {
    // Delete merchant_key_store
}

File: crates/router/src/db/merchant_key_store.rs [hunk 6]
```diff
@@ -1,6 +1,7 @@
 use error_stack::{IntoReport, ResultExt};
 use masking::Secret;
 #[cfg(feature = "accounts_cache")]
+use storage_impl::redis::cache::CacheKind;
```
Comment (Narayanbhat166) [inline crates/router/src/db/merchant_key_store.rs:4]: This import would be under the feature flag, and the next import should also be under the feature flag ( on line 5 ), can you merge these two imports?

File: crates/router/src/core/admin.rs [hunk 7]
```diff
@@ -465,11 +465,19 @@ pub async fn merchant_account_delete(
...
+    let is_merchant_account_deleted = db
         .delete_merchant_account_by_merchant_id(&merchant_id)
         .await
         .to_not_found_response(errors::ApiErrorResponse::MerchantAccountNotFound)?;
+    if is_merchant_account_deleted {
+        let is_merchant_key_store_deleted = db
+            .delete_merchant_key_store_by_merchant_id(&merchant_id)
+            .await
+            .to_not_found_response(errors::ApiErrorResponse::MerchantAccountNotFound)?;
+        is_deleted = is_merchant_account_deleted && is_merchant_key_store_deleted;
```
Comment (dalprahcd) [inline crates/router/src/core/admin.rs:479]: I realised that this could be simplified to ` is_deleted = is_merchant_key_store_deleted;`, but I prefer to leave explicit that `is_deleted` depends on both.

**Review by dracarys18 — APPROVED** [review]

**Review by Narayanbhat166 — APPROVED** [review]

**Review by SanchithHegde — APPROVED** [review]
Looks good to me!

Thanks for the PR, @dalprahcd!
