### PR TITLE
fix(chat): alter encryption logic for ai service

### LINKED ISSUE #9561: [BUG]: Decryption failure in chat prevents retrieval of conversation history
Internal users are unable to view their past chat conversations through the chat/ai/list endpoint, which is meant to be used for internal users. When attempting to retrieve the chat history, the system fails to decrypt the stored messages, resulting in error.

### PR DESCRIPTION
**Pull request by apoorvdixit88**
## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
This PR addresses an issue where chat conversation history could not be decrypted in the `chat/ai/list` endpoint. The root cause was an inconsistency between the encryption method used when storing chat interactions (`chat/ai/data`) and the decryption method used when retrieving them (`chat/ai/list`).

This change standardizes the encryption process to use the direct `GcmAes256` utility, ensuring compatibility between encryption and decryption, and resolving the data retrieval failures.

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context
Closes #9561

## How did you test it?
The list endpoint is working fine with new encryption logic:
```
curl --location 'http://localhost:8080/chat/ai/list?merchant_id=merchant_1758788495' \
--header 'Authorization: Bearer JWT' \
```

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

### CODE REVIEW

File: crates/router/src/utils/chat.rs [hunk 1]
```diff
@@ -29,29 +29,20 @@ pub async fn construct_hyperswitch_ai_interaction(
...
-    .and_then(|val| val.try_into_operation())
-    .change_context(errors::ApiErrorResponse::InternalServerError)
-    .attach_printable("Failed to encrypt response")?;
+    let encrypted_response_bytes = serde_json::to_vec(&response.response.clone())
+        .change_context(errors::ApiErrorResponse::InternalServerError)
+        .attach_printable("Failed to serialize response for encryption")
+        .and_then(|bytes| {
+            GcmAes256
+                .encode_message(&key, &bytes)
+                .map_err(|e| e.change_context(errors::ApiErrorResponse::InternalServerError))
```
Comment (SanchithHegde) [inline crates/router/src/utils/chat.rs]: Can't we call `change_context()` directly instead of calling `map_err()` and `change_context()`?

**Review by JeevaRamu0104 — APPROVED** [review]
