### PR TITLE
fix(chat): append request id to headers for chat request

### LINKED ISSUE #8679: Propage request id to chat service
Send request id to chat service in headers.

### PR DESCRIPTION
**Pull request by apoorvdixit88**
## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
Propagation request-id to chat service for consistency.
Propagate chat session id as well in request
Add count metric for chat api

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context
Closes #8679

## How did you test it?
Tested locally, x-request-id is getting populated correctly
```
curl --location 'http://localhost:8080/chat/ai/data' \
--header 'x-feature: integ-custom' \
--header 'x-chat-session-id: chat-ssdfasdsf' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer JWT' \

--data '{
        
        
        
        
            "message": "success rate"
    
}'
```
image
AI service logs
image
image

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

### CODE REVIEW

File: crates/router/src/core/chat.rs [hunk 1]
```diff
@@ -20,9 +20,9 @@ pub async fn get_data_from_hyperswitch_ai_workflow(
     state: SessionState,
     user_from_token: auth::UserFromToken,
     req: chat_api::ChatRequest,
+    request_id: String,
```
Comment (SanchithHegde) [inline crates/router/src/core/chat.rs]: Can we accept `&str` here instead (since you're anyway passing a reference further)?

File: crates/router/src/routes/chat.rs [hunk 2]
```diff
@@ -20,13 +22,29 @@ pub async fn get_data_from_hyperswitch_ai_workflow(
     payload: web::Json<chat_api::ChatRequest>,
 ) -> HttpResponse {
     let flow = Flow::GetDataFromHyperswitchAiFlow;
+    let request_id = match utils::get_request_id(&http_req) {
+        Ok(id) => id,
+        Err(err) => {
+            return api::log_and_return_error_response(err);
+        }
+    };
```
Comment (SanchithHegde) [inline crates/router/src/routes/chat.rs]: We already have a `get_request_id()` method on `AppState`? Can't we make use of that?

And do we necessarily need to error out if we can't obtain the request ID? Can't we treat is as an optional value?

**Review by SanchithHegde — DISMISSED** [review]

**Review by sai-harsha-vardhan — DISMISSED** [review]

**Review by JeevaRamu0104 — APPROVED** [review]

**Review by sai-harsha-vardhan — APPROVED** [review]

File: crates/router/src/routes/chat.rs [hunk 3]
```diff
@@ -1,11 +1,13 @@
 use actix_web::{web, HttpRequest, HttpResponse};
 #[cfg(feature = "olap")]
 use api_models::chat as chat_api;
+use common_utils;
```
Comment (SanchithHegde) [inline crates/router/src/routes/chat.rs]: Remove this useless import.

File: crates/router/src/routes/chat.rs [hunk 4]
```diff
@@ -20,13 +22,21 @@ pub async fn get_data_from_hyperswitch_ai_workflow(
     payload: web::Json<chat_api::ChatRequest>,
 ) -> HttpResponse {
     let flow = Flow::GetDataFromHyperswitchAiFlow;
+    let session_id = http_req
+        .headers()
+        .get(common_utils::consts::X_CHAT_SESSION_ID)
+        .and_then(|header_value| header_value.to_str().ok());
```
Comment (SanchithHegde) [inline crates/router/src/routes/chat.rs:27]: Is the frontend expected to send the session ID (or generate one in case of new sessions)?

File: crates/router/src/core/chat.rs [hunk 5]
```diff
@@ -20,9 +20,10 @@ pub async fn get_data_from_hyperswitch_ai_workflow(
     state: SessionState,
     user_from_token: auth::UserFromToken,
     req: chat_api::ChatRequest,
+    session_id: Option<&str>,
```
Comment (SanchithHegde) [inline crates/router/src/core/chat.rs:23]: Can include `session_id` as a field in the span:

```rust
#[instrument(skip_all, fields(?session_id))]
```

File: crates/router/src/routes/chat.rs (hunk 4 above)
Comment (apoorvdixit88) [reply crates/router/src/routes/chat.rs:27]: yes frontend will send the session ID

Comment (apoorvdixit88) [reply crates/router/src/routes/chat.rs:27]: @JeevaRamu0104
