### PR TITLE
fix(users): clear cookie and alter parsing for sso

### LINKED ISSUE #5146: fix: cover sso nitpicks and todo changes

### PR DESCRIPTION
**Pull request by apoorvdixit88**
## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
The PR
- removes cookie after rotate password and reset password
- refactor parsing for sso config, now it uses `serde json from value` instead of `parse value`
- refactors terminate auth select
- send bad request instead of internal server error if invalid id is passed to auth/select 

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context
closes #5146 

## How did you test it?
For bad request id for in auth select:
```
curl --location 'http://localhost:8080/user/auth/select' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer SPT' \
--data '{
    "id":"wrong id"
}'
```
Response
```
{
    "error": {
        "type": "invalid_request",
        "message": "Invalid user auth method operation",
        "code": "UR_44"
    }
}
```
For valid id Response token type can be `sso` or `totp`, (tested for both valid ids from db to get correct token type)
```
{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiYjJkNjMxZDUtMGQzMi00Y2IxLTg2MTQtNWVlNWI2MDczYTVkIiwicHVycG9zZSI6InNzbyIsIm9yaWdpbiI6ImFjY2VwdF9pbnZpdGF0aW9uX2Zyb21fZW1haWwiLCJwYXRoIjpbImF1dGhfc2VsZWN0Il0sImV4cCI6MTcxOTY2NjMxNX0.wz8bA3_xqD1J59t3N7jhMCpC-uQDZE2edMED93f8RrY",
    "token_type": "sso"
}
```

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

### CODE REVIEW

File: crates/router/src/core/user.rs [hunk 1]
```diff
@@ -2329,14 +2330,15 @@ pub async fn terminate_auth_select(
         .store
         .get_user_authentication_method_by_id(&req.id)
         .await
-        .change_context(UserErrors::InternalServerError)?;
+        .change_context(UserErrors::InvalidUserAuthMethodOperation)
+        .attach_printable("No authentication method found for the id")?;
```
Comment (racnan) [inline crates/router/src/core/user.rs:2334]: `InvalidUserAuthMethodOperation` error should only be thrown when id is not found.
not for every DB error.
use `to_not_found_response`

File: crates/router/src/core/user.rs [hunk 2]
```diff
@@ -2174,10 +2173,10 @@ pub async fn list_user_authentication_methods(
...
                 let auth_name = match (auth_method.auth_type, auth_method.public_config) {
                     (common_enums::UserAuthType::OpenIdConnect, Some(config)) => {
-                        let open_id_public_config: user_api::OpenIdConnectPublicConfig = config
-                            .parse_value("OpenIdConnectPublicConfig")
-                            .change_context(UserErrors::InternalServerError)
-                            .attach_printable("unable to parse generic data value")?;
+                        let open_id_public_config =
+                            serde_json::from_value::<user_api::OpenIdConnectPublicConfig>(config)
+                                .change_context(UserErrors::InternalServerError)
+                                .attach_printable("unable to parse generic data value")?;
```
Comment (racnan) [inline crates/router/src/core/user.rs:2179]: Change `attach_printable` message to be more specific.

File: crates/router/src/utils/user.rs [hunk 3]
```diff
@@ -286,3 +286,10 @@ fn get_oidc_key(oidc_state: &str) -> String {
 pub fn get_oidc_sso_redirect_url(state: &SessionState, provider: &str) -> String {
     format!("{}/redirect/oidc/{}", state.conf.user.base_url, provider)
 }
+
+pub fn is_sso_auth_type(auth_type: UserAuthType) -> bool {
```
Comment (racnan) [inline crates/router/src/utils/user.rs:290]: i think you can pass by reference here.

**Review by ThisIsMani — APPROVED** [review]

**Review by racnan — APPROVED** [review]
