### PR TITLE
fix(router): use `Connector` enum for `connector_name` field in `MerchantConnectorCreate`

### LINKED ISSUE #1023: [BUG] : `connector_name` in `MerchantConnectorCreate` accepts any value
### Bug Description

When creating a merchant connector account, the `connector_name` field is of string type. This would mean that any value can be passed to that field. There is no check done to validate whether the connector name given, is actually supported. This creates an issue in the payments flow when the `connector` is accessed as enum here https://github.com/juspay/hyperswitch/blob/58332f055e640ec810a3c6cc8e534f2f862e57dc/crates/router/src/types/api.rs#L144. The conversion function from string to enum can be found here https://github.com/juspay/hyperswitch/blob/58332f055e640ec810a3c6cc8e534f2f862e57dc/crates/router/src/types/api.rs#L185

### Expected Behavior

It should only accept the `connector_name` which are supported by hyperswitch.

### Actual Behavior

It accepts any value and then fails when creating the payment.

### Steps To Reproduce

Provide an unambiguous set of steps to reproduce this bug. Include code or configuration to reproduce, if relevant.
1. Create a `connector_account` with any `connector_name`. ( could be a typo ).
2. Create a payment with actual connector name.
3. The payment fails saying `Merchant connector account does not exist in our records`

### Context For The Bug

_No response_

### Environment

Are you using hyperswitch hosted version? No
If yes, please provide the value of the `x-request-id` response header for helping us debug your issue.

If not (or if building/running locally), please provide the following details:
1. Operating System or Linux distribution: Macos
2. Rust version (output of `rustc --version`): `rustc 1.68.2 (9eb3afe9e 2023-03-27)`
3. App version (output of `cargo r -- --version`): ``

### Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

No, but I'm happy to collaborate on a PR with someone else

### PR DESCRIPTION
**Pull request by deepanshu-iiitu**
## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
When creating a merchant connector account, the connector_name field is of string type. This would mean that any value can be passed to that field. There is no check done to validate whether the connector name given, is actually supported. This creates an issue in the payments flow when the connector is accessed as enum here

### Additional Changes

- [x] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

Fixes #1023.

## How did you test it?
Used Postman Call Payment Connector - Create to test the changes
Testing with a random connector and
Screenshot 2023-07-06 at 6 45 53 PM
 a supported connector:
Screenshot 2023-07-06 at 6 46 13 PM

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

### CODE REVIEW

File: crates/api_models/src/admin.rs [hunk 1]
```diff
@@ -392,7 +392,7 @@ pub struct MerchantConnectorCreate {
     pub connector_type: api_enums::ConnectorType,
     /// Name of the Connector
     #[schema(example = "stripe")]
```
Comment (SanchithHegde) [inline crates/api_models/src/admin.rs:394]:
```suggestion
    #[schema(value_type = Connector, example = "stripe")]
```

Please re-generate the OpenAPI spec once you've made this change.

**Review by SanchithHegde — COMMENTED** [review]
Other than that, looks good to me!

**Review by SanchithHegde — APPROVED** [review]

**Review by Narayanbhat166 — APPROVED** [review]
