### PR TITLE
fix(users): add password validations

### LINKED ISSUE #4412: BE Password specification
Make password have
Minimum number of characters.
At least one number, uppercase & lowercase characters and symbol. (This check is there in FE but not in BE).

### PR DESCRIPTION
**Pull request by Riddhiagrawal001**
## Type of Change

- [ ] Bugfix
- [ ] New feature
- [X] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Closes #4412 

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

The mandatory condition for the password field was just not be empty . Following the PR, the password field will be subject to the following checks:
1.The password must be between 8 and 50 characters in length.
2.It must include at least one uppercase character.
3.It must include at least one lowercase character.
4.It must include at least one special character.
5.It must include at least one numeric character.

## How did you test it?

1. Signup API ( local testing) 
```
curl --location 'http://localhost:8080/user/signup' \
--header 'Content-Type: application/json' \
--data-raw '{
    "email": "email value",
    "password": "456667sdvh",
    "country": "IN"
}'
```
Failure case response 
```
{
    "error": {
        "type": "invalid_request",
        "message": "Invalid Password",
        "code": "UR_09"
    }
}
```
2. Reset Password API (local testing)
```
curl --location 'http://localhost:8080/user/reset_password' \
--header 'Content-Type: application/json' \
--data '{
    "password": "456667sdvd",
    "token":"token from email after clicking Reset password in dashboard"
}'
```
Failure case response 
```
{
    "error": {
        "type": "invalid_request",
        "message": "Invalid Password",
        "code": "UR_09"
    }
}
``` 

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [ ] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

### CODE REVIEW

File: crates/router/src/types/domain/user.rs [hunk 1]
```diff
@@ -155,7 +155,20 @@ pub struct UserPassword(Secret<String>);
...
+        let has_special_character = password
+            .chars()
+            .any(|c| !(c.is_alphanumeric() || c.is_whitespace()));
+
+        let is_password_format_valid =
+            has_upper_case && has_lower_case && has_numeric_value && has_special_character;
+        let is_too_long = password.graphemes(true).count() > consts::user::MAX_PASSWORD_LENGTH;
+        let is_too_short = password.graphemes(true).count() < consts::user::MIN_PASSWORD_LENGTH;
+
+        if password.is_empty() || !is_password_format_valid || is_too_long || is_too_short {
```
Comment (apoorvdixit88) [inline crates/router/src/types/domain/user.rs:171]: password empty will be covered in too_short_case?

Comment (Riddhiagrawal001) [reply crates/router/src/types/domain/user.rs]: Yes it will . Removed `password.is_empty()` check

**Review by ThisIsMani — APPROVED** [review]

**Review by apoorvdixit88 — APPROVED** [review]
