### PR TITLE
fix(router): Propagate payment method type and subtype to split payment attempts (v2)

### LINKED ISSUE #10331: fix(router): Propagate correct payment method type and subtype in split payments (v2)
Currently the payment method type and subtype are not stored correctly in split payment attempt. We need to fix this

### PR DESCRIPTION
**Pull request by AnuthaDev**
## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

- Propagate PM type and subtype to split payment attempts

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

Closes #10331 

## How did you test it?

Payments Create:

Request:
```
{
    "id": "12345_pay_019ac9805b6874b395d2011c1b56bd0c",
    "status": "requires_payment_method",
    "amount_details": {
        "order_amount": 7500,
        "currency": "EUR",
        "shipping_cost": null,
        "order_tax_amount": null,
        "external_tax_calculation": "skip",
        "surcharge_calculation": "skip",
        "surcharge_amount": null,
        "tax_on_surcharge": null
    },
    "client_secret": "cs_019ac9805b8577308ff2a5bc3a6ed8aa",
    "profile_id": "pro_IBzD3DtWKKSAa8mhLOwc",
    "merchant_reference_id": null,
    "routing_algorithm_id": null,
    "capture_method": "automatic",
    "authentication_type": "no_three_ds",
    "billing": {
        "address": {
            "city": "San Fransico",
            "country": "US",
            "line1": "1467",
            "line2": "Harrison Street",
            "line3": "Harrison Street",
            "zip": "94122",
            "state": "California",
            "first_name": "joseph",
            "last_name": "Doe",
            "origin_zip": null
        },
        "phone": {
            "number": "123456789",
            "country_code": "+1"
        },
        "email": "user@gmail.com"
    },
    "shipping": {
        "address": {
            "city": "Karwar",
            "country": "US",
            "line1": null,
            "line2": null,
            "line3": null,
            "zip": "571201",
            "state": "California",
            "first_name": "John",
            "last_name": "Dough",
            "origin_zip": null
        },
        "phone": {
            "number": "123456789",
            "country_code": "+1"
        },
        "email": "example@example.com"
    },
    "customer_id": "12345_cus_019ac9802f1276b29375e960b0f36550",
    "customer_present": "present",
    "description": null,
    "return_url": null,
    "setup_future_usage": "on_session",
    "apply_mit_exemption": "Skip",
    "statement_descriptor": null,
    "order_details": [
        {
            "product_name": "Apple iphone 15",
            "quantity": 1,
            "amount": 1000,
            "tax_rate": null,
            "total_tax_amount": null,
            "requires_shipping": null,
            "product_img_link": null,
            "product_id": null,
            "category": null,
            "sub_category": null,
            "brand": null,
            "product_type": null,
            "product_tax_code": null,
            "description": null,
            "sku": null,
            "upc": null,
            "commodity_code": null,
            "unit_of_measure": null,
            "total_amount": null,
            "unit_discount_amount": null
        }
    ],
    "allowed_payment_method_types": null,
    "metadata": null,
    "connector_metadata": null,
    "feature_metadata": null,
    "payment_link_enabled": "Skip",
    "payment_link_config": null,
    "request_incremental_authorization": "false",
    "split_txns_enabled": "skip",
    "expires_on": "2025-11-28T08:22:03.798Z",
    "frm_metadata": null,
    "request_external_three_ds_authentication": "Skip",
    "payment_type": "normal",
    "enable_partial_authorization": null
}
```

Response:
```json
{
    "id": "12345_pay_019ac981bdac7ed19bfc73531ecabf04",
    "status": "requires_payment_method",
    "amount_details": {
        "order_amount": 7500,
        "currency": "EUR",
        "shipping_cost": null,
        "order_tax_amount": null,
        "external_tax_calculation": "skip",
        "surcharge_calculation": "skip",
        "surcharge_amount": null,
        "tax_on_surcharge": null
    },
    "client_secret": "cs_019ac981bdbd7b13b835d4bf94416caa",
    "profile_id": "pro_IBzD3DtWKKSAa8mhLOwc",
    "merchant_reference_id": null,
    "routing_algorithm_id": null,
    "capture_method": "automatic",
    "authentication_type": "no_three_ds",
    "billing": {
        "address": {
            "city": "San Fransico",
            "country": "US",
            "line1": "1467",
            "line2": "Harrison Street",
            "line3": "Harrison Street",
            "zip": "94122",
            "state": "California",
            "first_name": "joseph",
            "last_name": "Doe",
            "origin_zip": null
        },
        "phone": {
            "number": "123456789",
            "country_code": "+1"
        },
        "email": "user@gmail.com"
    },
    "shipping": {
        "address": {
            "city": "Karwar",
            "country": "US",
            "line1": null,
            "line2": null,
            "line3": null,
            "zip": "571201",
            "state": "California",
            "first_name": "John",
            "last_name": "Dough",
            "origin_zip": null
        },
        "phone": {
            "number": "123456789",
            "country_code": "+1"
        },
        "email": "example@example.com"
    },
    "customer_id": "12345_cus_019ac9802f1276b29375e960b0f36550",
    "customer_present": "present",
    "description": null,
    "return_url": null,
    "setup_future_usage": "on_session",
    "apply_mit_exemption": "Skip",
    "statement_descriptor": null,
    "order_details": [
        {
            "product_name": "Apple iphone 15",
            "quantity": 1,
            "amount": 1000,
            "tax_rate": null,
            "total_tax_amount": null,
            "requires_shipping": null,
            "product_img_link": null,
            "product_id": null,
            "category": null,
            "sub_category": null,
            "brand": null,
            "product_type": null,
            "product_tax_code": null,
            "description": null,
            "sku": null,
            "upc": null,
            "commodity_code": null,
            "unit_of_measure": null,
            "total_amount": null,
            "unit_discount_amount": null
        }
    ],
    "allowed_payment_method_types": null,
    "metadata": null,
    "connector_metadata": null,
    "feature_metadata": null,
    "payment_link_enabled": "Skip",
    "payment_link_config": null,
    "request_incremental_authorization": "false",
    "split_txns_enabled": "enable",
    "expires_on": "2025-11-28T08:23:34.487Z",
    "frm_metadata": null,
    "request_external_three_ds_authentication": "Skip",
    "payment_type": "normal",
    "enable_partial_authorization": null
}
```

Payments Confirm:

```
curl --location 'http://localhost:8080/v2/payments/12345_pay_019ac981bdac7ed19bfc73531ecabf04/confirm-intent' \
--header 'x-profile-id: pro_IBzD3DtWKKSAa8mhLOwc' \
--header 'x-client-secret: cs_019ac981bdbd7b13b835d4bf94416caa' \
--header 'Authorization: publishable-key=pk_dev_4ae8b1299f914f1a9d3fcbc871acd305,client-secret=cs_019ac981bdbd7b13b835d4bf94416caa' \
--header 'Content-Type: application/json' \
--header 'api-key: pk_dev_4ae8b1299f914f1a9d3fcbc871acd305' \
--data '{
    "payment_method_data": {
        "card": {
            "card_cvc": "737",
            "card_exp_month": "03",
            "card_exp_year": "30",
            "card_number": "4000620000000007",
            "card_holder_name": "joseph Doe"
        }
    },
    "payment_method_type": "card",
    "payment_method_subtype": "card",
    "split_payment_method_data": [
        {
            "payment_method_data": {
                "gift_card": {
                    "givex": {
                        "number": "6036280000000000000",
                        "cvc": "123"
                    }
                }
            },
            "payment_method_type": "gift_card",
            "payment_method_subtype": "givex"
        }
    ],
    "browser_info": {
        "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
        "accept_header": "text\\/html,application\\/xhtml+xml,application\\/xml;q=0.9,image\\/webp,image\\/apng,*\\/*;q=0.8",
        "language": "en-GB",
        "color_depth": 24,
        "screen_height": 1440,
        "screen_width": 2560,
        "time_zone": -330,
        "java_enabled": true,
        "java_script_enabled": true,
        "ip_address": "0.0.0.0"
    }
}'
```

Response:
```json
{
    "id": "12345_pay_019ac981bdac7ed19bfc73531ecabf04",
    "status": "succeeded",
    "amount": {
        "order_amount": 7500,
        "currency": "EUR",
        "shipping_cost": null,
        "order_tax_amount": null,
        "external_tax_calculation": "skip",
        "surcharge_calculation": "skip",
        "surcharge_amount": null,
        "tax_on_surcharge": null,
        "net_amount": 7500,
        "amount_to_capture": null,
        "amount_capturable": 0,
        "amount_captured": 7500
    },
    "customer_id": "12345_cus_019ac9802f1276b29375e960b0f36550",
    "connector": "adyen",
    "created": "2025-11-28T08:08:34.487Z",
    "modified_at": "2025-11-28T08:09:31.752Z",
    "payment_method_data": {
        "billing": null
    },
    "payment_method_type": "card",
    "payment_method_subtype": "card",
    "connector_transaction_id": "R3MZJHJR97L5K5V5",
    "connector_reference_id": "12345_att_019ac98298097300a09f92a3528e8d87",
    "merchant_connector_id": "mca_hclZxNurTORUBA8ZyYAI",
    "browser_info": null,
    "error": null,
    "shipping": null,
    "billing": null,
    "attempts": null,
    "connector_token_details": null,
    "payment_method_id": null,
    "next_action": null,
    "return_url": "https://google.com/success",
    "authentication_type": "no_three_ds",
    "authentication_type_applied": "no_three_ds",
    "is_iframe_redirection_enabled": null,
    "merchant_reference_id": null,
    "raw_connector_response": null,
    "feature_metadata": null,
    "metadata": null
}
```

Payments Retrieve with expand attempts:

Request:

```
curl --location 'http://localhost:8080/v2/payments/12345_pay_019abf3450887e5194dce8fb474490f7?expand_attempts=true' \
--header 'x-profile-id: pro_c28IGkmBcjEIgWaphtOJ' \
--header 'Authorization: api-key=dev_5RCYCaNRSLe8vvdlRYSg3WbIzTSKPMKfg2me1kFzRJ565uRfr8oPTcVF5nZsKjaW' \
--data ''
```

Response:
```json
{
    "id": "12345_pay_019abf3450887e5194dce8fb474490f7",
    "status": "succeeded",
    "amount": {
        "order_amount": 7500,
        "currency": "EUR",
        "shipping_cost": null,
        "order_tax_amount": null,
        "external_tax_calculation": "skip",
        "surcharge_calculation": "skip",
        "surcharge_amount": null,
        "tax_on_surcharge": null,
        "net_amount": 5000,
        "amount_to_capture": null,
        "amount_capturable": 0,
        "amount_captured": 5000
    },
    "customer_id": "12345_cus_019abf0d489c7b43983aa0f35fe5dc09",
    "connector": "adyen",
    "created": "2025-11-26T08:07:48.117Z",
    "modified_at": "2025-11-26T08:08:08.947Z",
    "payment_method_data": {
        "billing": null
    },
    "payment_method_type": "gift_card",
    "payment_method_subtype": "givex",
    "connector_transaction_id": "XK8M3D32G3C73PV5",
    "connector_reference_id": "12345_att_019abf349d8f7820a44d7f65654fe031",
    "merchant_connector_id": "mca_WiUegabddaR3Bbxx8cPG",
    "browser_info": null,
    "error": null,
    "shipping": {
        "address": {
            "city": "Karwar",
            "country": "US",
            "line1": null,
            "line2": null,
            "line3": null,
            "zip": "571201",
            "state": "California",
            "first_name": "John",
            "last_name": "Dough",
            "origin_zip": null
        },
        "phone": {
            "number": "123456789",
            "country_code": "+1"
        },
        "email": "example@example.com"
    },
    "billing": {
        "address": {
            "city": "San Fransico",
            "country": "US",
            "line1": "1467",
            "line2": "Harrison Street",
            "line3": "Harrison Street",
            "zip": "94122",
            "state": "California",
            "first_name": "joseph",
            "last_name": "Doe",
            "origin_zip": null
        },
        "phone": {
            "number": "123456789",
            "country_code": "+1"
        },
        "email": "user@gmail.com"
    },
    "attempts": [
        {
            "id": "12345_att_019abf3498d17351a796abb1f61c2a6e",
            "status": "charged",
            "amount": {
                "net_amount": 2500,
                "amount_to_capture": null,
                "surcharge_amount": null,
                "tax_on_surcharge": null,
                "amount_capturable": 0,
                "shipping_cost": null,
                "order_tax_amount": null
            },
            "connector": "adyen",
            "error": null,
            "authentication_type": "no_three_ds",
            "created_at": "2025-11-26T08:08:06.609Z",
            "modified_at": "2025-11-26T08:08:07.818Z",
            "cancellation_reason": null,
            "payment_token": null,
            "connector_metadata": null,
            "payment_experience": null,
            "payment_method_type": "card",
            "connector_reference_id": "12345_att_019abf3498d17351a796abb1f61c2a6e",
            "payment_method_subtype": "card",
            "connector_payment_id": {
                "TxnId": "BG5KZJS9JBCDCQV5"
            },
            "payment_method_id": null,
            "client_source": null,
            "client_version": null,
            "feature_metadata": null,
            "payment_method_data": null
        },
        {
            "id": "12345_att_019abf349d8f7820a44d7f65654fe031",
            "status": "charged",
            "amount": {
                "net_amount": 5000,
                "amount_to_capture": null,
                "surcharge_amount": null,
                "tax_on_surcharge": null,
                "amount_capturable": 0,
                "shipping_cost": null,
                "order_tax_amount": null
            },
            "connector": "adyen",
            "error": null,
            "authentication_type": "no_three_ds",
            "created_at": "2025-11-26T08:08:07.823Z",
            "modified_at": "2025-11-26T08:08:08.941Z",
            "cancellation_reason": null,
            "payment_token": null,
            "connector_metadata": null,
            "payment_experience": null,
            "payment_method_type": "gift_card",
            "connector_reference_id": "12345_att_019abf349d8f7820a44d7f65654fe031",
            "payment_method_subtype": "givex",
            "connector_payment_id": {
                "TxnId": "XK8M3D32G3C73PV5"
            },
            "payment_method_id": null,
            "client_source": null,
            "client_version": null,
            "feature_metadata": null,
            "payment_method_data": null
        }
    ],
    "connector_token_details": null,
    "payment_method_id": null,
    "next_action": null,
    "return_url": "https://google.com/success",
    "authentication_type": "no_three_ds",
    "authentication_type_applied": null,
    "is_iframe_redirection_enabled": null,
    "merchant_reference_id": null,
    "raw_connector_response": null,
    "feature_metadata": null,
    "metadata": null
}
```

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

### CODE REVIEW

File: crates/router/src/core/split_payments.rs [hunk 1]
```diff
@@ -175,25 +175,39 @@ async fn get_payment_method_amount_split(
...
-                PaymentMethodData::GiftCard(Box::new(gift_card_card.to_owned())),
-                amount_to_use,
-            )))
+            Some(Ok(split_payments::PaymentMethodDetailsWithSplitAmount {
+                split_amount: amount_to_use,
+                payment_method_details: split_payments::PaymentMethodDetails {
+                    payment_method_data: PaymentMethodData::GiftCard(Box::new(
+                        gift_card_card.to_owned(),
+                    )),
+                    payment_method_type: common_enums::PaymentMethod::GiftCard,
```
Comment (sai-harsha-vardhan) [inline crates/router/src/core/split_payments.rs:184]: please populate this from domain data instead of hardcoding

**Review by sai-harsha-vardhan — APPROVED** [review]

File: crates/router/src/core/split_payments.rs (hunk 1 above)
Comment (AnuthaDev) [reply crates/router/src/core/split_payments.rs:184]: Currently we are using GiftCard only, so its fine to hardcode.
