### PR TITLE
fix(nexinets): limit connector_request_reference_id to 30 characters using nanoid

### LINKED ISSUE #9870: [BUG] Fix length issue of `connector_request_reference_id` for nexinets in v2
### Bug Description

When creating a payment through the Nexinets connector in V2 flow, the `connector_request_reference_id`exceeds the allowed length expected by the connector API. 

### Expected Behavior

Payment creation should succeed without any validation errors, and the connector request should pass.

### Actual Behavior

When creating a payment through the Nexinets connector in V2 flow, the `connector_request_reference_id`exceeds the allowed length expected by the connector API. 

### Environment

Are you using hyperswitch hosted version? Yes/No
If yes, please provide the value of the `x-request-id` response header to help us debug your issue.

If not (or if building/running locally), please provide the following details:
1. Operating System or Linux distribution:
2. Rust version (output of `rustc --version`): ``
3. App version (output of `cargo r --features vergen -- --version`): ``

### Have you spent some time checking if this bug has been raised before?

- [x] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [x] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

Yes, I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by ayush22667**
## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

When creating a payment through the Nexinets connector in V2 flow, the `connector_request_reference_id` exceeds the allowed length(30) expected by the connector. Add a new nexinets_constants module containing MAX_PAYMENT_REFERENCE_ID_LENGTH = 30 .

### Additional Changes

- [ ] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

closes #9870 

## How did you test it?

Payment Create:
```
curl --location 'http://localhost:8080/v2/payments/create-intent' \
--header 'api-key: dev_UZ6PSsxZqbf5nzpfFpqpefibgZEUleTcGycwOmslp0PeRsIDIzIJUpQubHKHmYta' \
--header 'Content-Type: application/json' \
--header 'x-profile-id: pro_b6cDruHGxBo26XjfO9Ta' \
--header 'Authorization: api-key=dev_UZ6PSsxZqbf5nzpfFpqpefibgZEUleTcGycwOmslp0PeRsIDIzIJUpQubHKHmYta' \
--data-raw '{
    "amount_details": {
        "order_amount": 100,
        "currency": "EUR"
    },
    "capture_method":"automatic",
    "authentication_type": "no_three_ds",
    "billing": {
        "address": {
            "first_name": "John",
            "last_name": "Dough"
        },
        "email": "example@example.com"
    },
    "shipping": {
        "address": {
            "first_name": "John",
            "last_name": "Dough",
            "city": "Karwar",
            "zip": "581301",
            "state": "Karnataka"
        },
        "email": "example@example.com"
    }
}'
```
Response:
```
{
    "id": "12345_pay_0199ebc9142d7cd396ebea5df1933391",
    "status": "requires_payment_method",
    "amount_details": {
        "order_amount": 100,
        "currency": "EUR",
        "shipping_cost": null,
        "order_tax_amount": null,
        "external_tax_calculation": "skip",
        "surcharge_calculation": "skip",
        "surcharge_amount": null,
        "tax_on_surcharge": null
    },
    "client_secret": "cs_0199ebc914407db1979414cbbe02f4a9",
    "profile_id": "pro_b6cDruHGxBo26XjfO9Ta",
    "merchant_reference_id": null,
    "routing_algorithm_id": null,
    "capture_method": "automatic",
    "authentication_type": "no_three_ds",
    "billing": {
        "address": {
            "city": null,
            "country": null,
            "line1": null,
            "line2": null,
            "line3": null,
            "zip": null,
            "state": null,
            "first_name": "John",
            "last_name": "Dough",
            "origin_zip": null
        },
        "phone": null,
        "email": "example@example.com"
    },
    "shipping": {
        "address": {
            "city": "Karwar",
            "country": null,
            "line1": null,
            "line2": null,
            "line3": null,
            "zip": "581301",
            "state": "Karnataka",
            "first_name": "John",
            "last_name": "Dough",
            "origin_zip": null
        },
        "phone": null,
        "email": "example@example.com"
    },
    "customer_id": null,
    "customer_present": "present",
    "description": null,
    "return_url": null,
    "setup_future_usage": "on_session",
    "apply_mit_exemption": "Skip",
    "statement_descriptor": null,
    "order_details": null,
    "allowed_payment_method_types": null,
    "metadata": null,
    "connector_metadata": null,
    "feature_metadata": null,
    "payment_link_enabled": "Skip",
    "payment_link_config": null,
    "request_incremental_authorization": "false",
    "split_txns_enabled": "skip",
    "expires_on": "2025-10-16T07:05:47.739Z",
    "frm_metadata": null,
    "request_external_three_ds_authentication": "Skip",
    "payment_type": "normal",
    "enable_partial_authorization": null
}
```
Confirm Intent:
```
curl --location 'http://localhost:8080/v2/payments/12345_pay_0199ebc9142d7cd396ebea5df1933391/confirm-intent' \
--header 'x-client-secret: cs_0199ebc914407db1979414cbbe02f4a9' \
--header 'x-profile-id: pro_b6cDruHGxBo26XjfO9Ta' \
--header 'Authorization: api-key=dev_UZ6PSsxZqbf5nzpfFpqpefibgZEUleTcGycwOmslp0PeRsIDIzIJUpQubHKHmYta' \
--header 'Content-Type: application/json' \
--header 'api-key: pk_dev_9005f4ca178b433aaedb59dee8fc7f52' \
--data '{
    "payment_method_data": {
        "card": {
            "card_number": "4012001038443335",
            "card_exp_month": "03",
            "card_exp_year": "30",
            "card_holder_name": "John Doe",
            "card_cvc": "737"
        }
    },
    
    "payment_method_type": "card",
    "payment_method_subtype": "credit",
     "browser_info": {
        "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
        "accept_header": "text\\/html,application\\/xhtml+xml,application\\/xml;q=0.9,image\\/webp,image\\/apng,*\\/*;q=0.8",
        "language": "en-GB",
        "color_depth": 24,
        "screen_height": 1440,
        "screen_width": 2560,
        "time_zone": -330,
        "java_enabled": true,
        "java_script_enabled": true,
        "ip_address": "0.0.0.0"
    }
}'
```
Response:
```
{
    "id": "12345_pay_0199ebc9142d7cd396ebea5df1933391",
    "status": "succeeded",
    "amount": {
        "order_amount": 100,
        "currency": "EUR",
        "shipping_cost": null,
        "order_tax_amount": null,
        "external_tax_calculation": "skip",
        "surcharge_calculation": "skip",
        "surcharge_amount": null,
        "tax_on_surcharge": null,
        "net_amount": 100,
        "amount_to_capture": null,
        "amount_capturable": 0,
        "amount_captured": 100
    },
    "customer_id": null,
    "connector": "nexinets",
    "created": "2025-10-16T06:50:47.739Z",
    "modified_at": "2025-10-16T06:51:21.256Z",
    "payment_method_data": {
        "billing": null
    },
    "payment_method_type": "card",
    "payment_method_subtype": "credit",
    "connector_transaction_id": "transaction_pizumumoxc",
    "connector_reference_id": "vxy0be6b90",
    "merchant_connector_id": "mca_A68sfia4LoffOMxoVc83",
    "browser_info": null,
    "error": null,
    "shipping": null,
    "billing": null,
    "attempts": null,
    "connector_token_details": {
        "token": "paymentinstrument_1bprm7t9zc",
        "connector_token_request_reference_id": "3oyQE9hVg6WqS6PFc8"
    },
    "payment_method_id": null,
    "next_action": null,
    "return_url": "https://google.com/success",
    "authentication_type": "no_three_ds",
    "authentication_type_applied": "no_three_ds",
    "is_iframe_redirection_enabled": null,
    "merchant_reference_id": null,
    "raw_connector_response": null,
    "feature_metadata": null,
    "metadata": null
}
```

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

### CODE REVIEW

File: crates/hyperswitch_connectors/src/connectors/nexinets.rs [hunk 1]
```diff
@@ -882,6 +884,24 @@ impl ConnectorSpecifications for Nexinets {
...
+    fn generate_connector_request_reference_id(
+        &self,
+        payment_intent: &PaymentIntent,
+        _payment_attempt: &PaymentAttempt,
+    ) -> String {
+        // The length of merchantOrderId for Nexinets should not exceed 30 characters.
+        payment_intent
+            .merchant_reference_id
+            .as_ref()
+            .map(|id| id.get_string_repr().to_owned())
```
Comment (deepanshu-iiitu) [inline crates/hyperswitch_connectors/src/connectors/nexinets.rs:898]: What happens when this merchant_reference_id>30 chars?

Comment (ayush22667) [reply crates/hyperswitch_connectors/src/connectors/nexinets.rs:898]: It will give error `Bad value for 'merchantOrderId'. Expected: unique string between 1 and 30 characters.`

**Review by hrithikesh026 — DISMISSED** [review]
No core changes

**Review by AkshayaFoiger — APPROVED** [review]

**Comment by hrithikesh026** [comment]
Can also verify if the generated id is being persisted in DB
