### PR TITLE
fix(payments): add connector metadata parsing and order category to payment router data

### LINKED ISSUE #9824: [BUG]Noon Connector V2 API Failure - Missing order_category in Authorize flow
### Bug Description

The Noon Connector V2 API is failing in the payment flow with the error “Missing required param: order_category.” This happens because the connector_metadata is not being extracted properly in the V2 confirm-intent flow, which causes the order_category field to be None. 

### Expected Behavior

The Noon Connector V2 API should extract order_category from connector_metadata during the payment flow. When a request with valid connector_metadata is sent, the order_category value should be passed correctly to the connector, and the payment should proceed without errors.

### Actual Behavior

The connector_metadata is not being extracted in the V2 payment flow, causing the `order_category` field to be None. As a result, the API returns the error `Missing required param: order_category`, and the payment flow fails to complete.

### Steps To Reproduce

Provide an unambiguous set of steps to reproduce this bug. Include code or configuration to reproduce, if relevant.

### Context For The Bug

_No response_

### Environment

Are you using hyperswitch hosted version? Yes/No
If yes, please provide the value of the `x-request-id` response header to help us debug your issue.

If not (or if building/running locally), please provide the following details:
1. Operating System or Linux distribution:
2. Rust version (output of `rustc --version`): ``
3. App version (output of `cargo r --features vergen -- --version`): ``

### Have you spent some time checking if this bug has been raised before?

- [x] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [x] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

Yes, I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by ayush22667**
## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
The Noon Connector V2 API is failing in the payment flow with the error `Missing required param: order_category.` This happens because the connector_metadata is not being extracted in the V2 confirm-intent flow, which causes the order_category field to be None. The fix involves correctly parsing connector_metadata and ensuring the order_category value is passed from it.

### Additional Changes

- [x] This PR modifies the API contract
- [ ] This PR modifies the database schema
- [ ] This PR modifies application configuration/environment variables

## Motivation and Context

closes #9824 

## How did you test it?

Payment Create : 
```
curl --location 'http://localhost:8080/v2/payments' \
--header 'api-key: dev_xob8X5unmvgpvxyrojXCRCI7uDY4QnAA1K9keYrZ2SUdxd8R06fHfhw8Z0KrdMTY' \
--header 'Content-Type: application/json' \
--header 'x-profile-id: pro_ujMrnFy6c56AQkrp5QMn' \
--header 'Authorization: api-key=dev_xob8X5unmvgpvxyrojXCRCI7uDY4QnAA1K9keYrZ2SUdxd8R06fHfhw8Z0KrdMTY' \
--data-raw '{
    "amount_details": {
      "order_amount": 6540,
      "currency": "AED"
    },
    "capture_method": "automatic",
    "authentication_type": "no_three_ds",
    "customer_id": "12345_cus_0199e1767bb47751bb4bdead294553eb",
    "description": "CIT payment with multi-use mandate for Noon",
    "setup_future_usage": "off_session",
    "billing": {
      "address": {
        "first_name": "John",
        "last_name": "Doe",
        "city": "Dubai",
        "state": "Dubai",
        "zip": "94122",
        "country": "AE"
      },
      "email": "john.doe@example.com"
    },
    "shipping": {
      "address": {
        "first_name": "John",
        "last_name": "Doe",
        "city": "Dubai",
        "state": "Dubai",
        "zip": "94122",
        "country": "AE"
      },
      "email": "john.doe@example.com"
    },
    "connector_metadata": {
      "noon": {
        "order_category": "pay"
      }
    },
    "payment_method_data": {
      "card": {
        "card_number": "4000000000002701",
        "card_exp_month": "10",
        "card_exp_year": "2030",
        "card_holder_name": "John Doe",
        "card_cvc": "257"
      }
    },
    "payment_method_type": "card",
    "payment_method_subtype": "credit"
  }'
```
Response:
```
{
    "id": "12345_pay_0199e17e9b8e7131a34a1d74f75952d5",
    "status": "succeeded",
    "amount": {
        "order_amount": 6540,
        "currency": "AED",
        "shipping_cost": null,
        "order_tax_amount": null,
        "external_tax_calculation": "skip",
        "surcharge_calculation": "skip",
        "surcharge_amount": null,
        "tax_on_surcharge": null,
        "net_amount": 6540,
        "amount_to_capture": null,
        "amount_capturable": 0,
        "amount_captured": 6540
    },
    "customer_id": "12345_cus_0199e1767bb47751bb4bdead294553eb",
    "connector": "noon",
    "created": "2025-10-14T06:53:15.023Z",
    "modified_at": "2025-10-14T06:53:17.092Z",
    "payment_method_data": {
        "billing": null
    },
    "payment_method_type": "card",
    "payment_method_subtype": "credit",
    "connector_transaction_id": "280808415907",
    "connector_reference_id": "12345_att_0199e17e9ba37d21ae7bbe65208285a6",
    "merchant_connector_id": "mca_Jqv8Dg7oUHX3nrHFwCAZ",
    "browser_info": null,
    "error": null,
    "shipping": null,
    "billing": null,
    "attempts": null,
    "connector_token_details": null,
    "payment_method_id": null,
    "next_action": null,
    "return_url": "https://google.com/success",
    "authentication_type": "no_three_ds",
    "authentication_type_applied": "no_three_ds",
    "is_iframe_redirection_enabled": null,
    "merchant_reference_id": null,
    "raw_connector_response": null,
    "feature_metadata": null,
    "metadata": null
}
```

## Checklist

- [x] I formatted the code `cargo +nightly fmt --all`
- [x] I addressed lints thrown by `cargo clippy`
- [x] I reviewed the submitted code
- [ ] I added unit tests for my changes where possible

### CODE REVIEW

File: crates/router/src/core/payments/transformers.rs [hunk 1]
```diff
@@ -377,6 +377,23 @@ pub async fn construct_payment_router_data_for_authorize<'a>(
                 .change_context(errors::ApiErrorResponse::InternalServerError)
                 .attach_printable("Failed to parse AdditionalPaymentData from payment_data.payment_attempt.payment_method_data")?;
 
+    let connector_metadata = payment_data
+        .payment_intent
+        .connector_metadata
```
Comment (hrithikesh026) [inline crates/router/src/core/payments/transformers.rs]: This field in domain PaymentIntent can be changed to `ConnectorMetadata` type. So that you don't need to deserialize here.

File: crates/router/src/core/payments/transformers.rs [hunk 2]
```diff
@@ -377,6 +377,23 @@ pub async fn construct_payment_router_data_for_authorize<'a>(
...
+        .clone()
+        .map(|cm| {
+            cm.parse_value::<api_models::payments::ConnectorMetadata>("ConnectorMetadata")
+                .change_context(errors::ApiErrorResponse::InternalServerError)
+                .attach_printable("Failed parsing ConnectorMetadata")
+        })
+        .transpose()?;
+
+    let order_category = connector_metadata.as_ref().and_then(|cm| {
```
Comment (sai-harsha-vardhan) [inline crates/router/src/core/payments/transformers.rs:392]: Why do we have to do this parsing in core and set in router data? This can be extracted at connector layer itself right?

**Review by sai-harsha-vardhan — APPROVED** [review]
